// Generated by winbindgen — do not edit.
const std = @import("std");
const win_core = @import("win-core");

pub const HRESULT = win_core.HRESULT;
pub const HSTRING = win_core.HSTRING;
pub const GUID = win_core.GUID;
pub const BOOL = win_core.BOOL;
pub const NTSTATUS = win_core.NTSTATUS;
pub const BOOLEAN = win_core.BOOLEAN;
pub const IInspectable_Vtbl = win_core.IInspectable_Vtbl;
pub const IUnknown_Vtbl = win_core.IUnknown_Vtbl;
pub const IUnknown = win_core.IUnknown;

pub const IID_IAsyncAction: GUID = .{
    .data1 = 0x5A648006,
    .data2 = 0x843A,
    .data3 = 0x4DA9,
    .data4 = .{ 0x86, 0x5B, 0x9D, 0x26, 0xE5, 0xDF, 0xAD, 0x7B },
};
pub const IID_IAsyncInfo: GUID = .{
    .data1 = 0x00000036,
    .data2 = 0x0000,
    .data3 = 0x0000,
    .data4 = .{ 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46 },
};
pub const IID_IClosable: GUID = .{
    .data1 = 0x30D5A829,
    .data2 = 0x7FA4,
    .data3 = 0x4026,
    .data4 = .{ 0x83, 0xBB, 0xD7, 0x5B, 0xAE, 0x4E, 0xA9, 0x9E },
};
pub const IID_IDeferral: GUID = .{
    .data1 = 0xD6269732,
    .data2 = 0x3B7F,
    .data3 = 0x46A7,
    .data4 = .{ 0xB4, 0x0B, 0x4F, 0xDC, 0xA2, 0xA2, 0xC6, 0x93 },
};
pub const IID_IDeferralFactory: GUID = .{
    .data1 = 0x65A1ECC5,
    .data2 = 0x3FB5,
    .data3 = 0x4832,
    .data4 = .{ 0x8C, 0xA9, 0xF0, 0x61, 0xB2, 0x81, 0xD1, 0x3A },
};
pub const IID_IGetActivationFactory: GUID = .{
    .data1 = 0x4EDB8EE2,
    .data2 = 0x96DD,
    .data3 = 0x49A7,
    .data4 = .{ 0x94, 0xF7, 0x46, 0x07, 0xDD, 0xAB, 0x8E, 0x3C },
};
pub const IID_IGuidHelperStatics: GUID = .{
    .data1 = 0x59C7966B,
    .data2 = 0xAE52,
    .data3 = 0x5283,
    .data4 = .{ 0xAD, 0x7F, 0xA1, 0xB9, 0xE9, 0x67, 0x8A, 0xDD },
};
pub const IID_IMemoryBuffer: GUID = .{
    .data1 = 0xFBC4DD2A,
    .data2 = 0x245B,
    .data3 = 0x11E4,
    .data4 = .{ 0xAF, 0x98, 0x68, 0x94, 0x23, 0x26, 0x0C, 0xF8 },
};
pub const IID_IMemoryBufferFactory: GUID = .{
    .data1 = 0xFBC4DD2B,
    .data2 = 0x245B,
    .data3 = 0x11E4,
    .data4 = .{ 0xAF, 0x98, 0x68, 0x94, 0x23, 0x26, 0x0C, 0xF8 },
};
pub const IID_IMemoryBufferReference: GUID = .{
    .data1 = 0xFBC4DD29,
    .data2 = 0x245B,
    .data3 = 0x11E4,
    .data4 = .{ 0xAF, 0x98, 0x68, 0x94, 0x23, 0x26, 0x0C, 0xF8 },
};
pub const IID_IPropertyValue: GUID = .{
    .data1 = 0x4BD682DD,
    .data2 = 0x7554,
    .data3 = 0x40E9,
    .data4 = .{ 0x9A, 0x9B, 0x82, 0x65, 0x4E, 0xDE, 0x7E, 0x62 },
};
pub const IID_IPropertyValueStatics: GUID = .{
    .data1 = 0x629BDBC8,
    .data2 = 0xD932,
    .data3 = 0x4FF4,
    .data4 = .{ 0x96, 0xB9, 0x8D, 0x96, 0xC5, 0xC1, 0xE8, 0x58 },
};
pub const IID_IStringable: GUID = .{
    .data1 = 0x96369F54,
    .data2 = 0x8EB6,
    .data3 = 0x48F0,
    .data4 = .{ 0xAB, 0xCE, 0xC1, 0xB2, 0x11, 0xE6, 0x27, 0xC3 },
};
pub const IID_IUriEscapeStatics: GUID = .{
    .data1 = 0xC1D432BA,
    .data2 = 0xC824,
    .data3 = 0x4452,
    .data4 = .{ 0xA7, 0xFD, 0x51, 0x2B, 0xC3, 0xBB, 0xE9, 0xA1 },
};
pub const IID_IUriRuntimeClass: GUID = .{
    .data1 = 0x9E365E57,
    .data2 = 0x48B2,
    .data3 = 0x4160,
    .data4 = .{ 0x95, 0x6F, 0xC7, 0x38, 0x51, 0x20, 0xBB, 0xFC },
};
pub const IID_IUriRuntimeClassFactory: GUID = .{
    .data1 = 0x44A9796F,
    .data2 = 0x723E,
    .data3 = 0x4FDF,
    .data4 = .{ 0xA2, 0x18, 0x03, 0x3E, 0x75, 0xB0, 0xC0, 0x84 },
};
pub const IID_IUriRuntimeClassWithAbsoluteCanonicalUri: GUID = .{
    .data1 = 0x758D9661,
    .data2 = 0x221C,
    .data3 = 0x480F,
    .data4 = .{ 0xA3, 0x39, 0x50, 0x65, 0x66, 0x73, 0xF4, 0x6F },
};
pub const IID_IWwwFormUrlDecoderEntry: GUID = .{
    .data1 = 0x125E7431,
    .data2 = 0xF678,
    .data3 = 0x4E8E,
    .data4 = .{ 0xB6, 0x70, 0x20, 0xA9, 0xB0, 0x6C, 0x51, 0x2D },
};
pub const IID_IWwwFormUrlDecoderRuntimeClass: GUID = .{
    .data1 = 0xD45A0451,
    .data2 = 0xF225,
    .data3 = 0x4542,
    .data4 = .{ 0x92, 0x96, 0x0E, 0x1D, 0xF5, 0xD2, 0x54, 0xDF },
};
pub const IID_IWwwFormUrlDecoderRuntimeClassFactory: GUID = .{
    .data1 = 0x5B8C6B3D,
    .data2 = 0x24AE,
    .data3 = 0x41B5,
    .data4 = .{ 0xA1, 0xBF, 0xF0, 0xC3, 0xD5, 0x44, 0x84, 0x5B },
};
pub const AsyncStatus = enum(i32) {
    Canceled = 2,
    Completed = 1,
    Error = 3,
    Started = 0,
    _,
};
pub const PropertyType = enum(i32) {
    Empty = 0,
    UInt8 = 1,
    Int16 = 2,
    UInt16 = 3,
    Int32 = 4,
    UInt32 = 5,
    Int64 = 6,
    UInt64 = 7,
    Single = 8,
    Double = 9,
    Char16 = 10,
    Boolean = 11,
    String = 12,
    Inspectable = 13,
    DateTime = 14,
    TimeSpan = 15,
    Guid = 16,
    Point = 17,
    Size = 18,
    Rect = 19,
    OtherType = 20,
    UInt8Array = 1025,
    Int16Array = 1026,
    UInt16Array = 1027,
    Int32Array = 1028,
    UInt32Array = 1029,
    Int64Array = 1030,
    UInt64Array = 1031,
    SingleArray = 1032,
    DoubleArray = 1033,
    Char16Array = 1034,
    BooleanArray = 1035,
    StringArray = 1036,
    InspectableArray = 1037,
    DateTimeArray = 1038,
    TimeSpanArray = 1039,
    GuidArray = 1040,
    PointArray = 1041,
    SizeArray = 1042,
    RectArray = 1043,
    OtherTypeArray = 1044,
    _,
};
pub const DateTime = extern struct {
    UniversalTime: i64,
};
pub const EventRegistrationToken = extern struct {
    Value: i64,
};
pub const HResult = extern struct {
    Value: i32,
};
pub const Point = extern struct {
    X: f32,
    Y: f32,
};
pub const Rect = extern struct {
    X: f32,
    Y: f32,
    Width: f32,
    Height: f32,
};
pub const Size = extern struct {
    Width: f32,
    Height: f32,
};
pub const TimeSpan = extern struct {
    Duration: i64,
};
pub const IAsyncAction = extern struct {
    vtable: *const IAsyncAction_Vtbl,
    pub const Vtbl = IAsyncAction_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x5a648006, .data2 = 0x843a, .data3 = 0x4da9, .data4 = .{ 0x86, 0x5b, 0x9d, 0x26, 0xe5, 0xdf, 0xad, 0x7b } };
    pub fn QueryInterface(self: *const IAsyncAction, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IAsyncAction) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IAsyncAction) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IAsyncAction, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn put_Completed(self: *const IAsyncAction, p0: *AsyncActionCompletedHandler) callconv(.winapi) HRESULT {
        return self.vtable.put_Completed(self, p0);
    }
    pub fn get_Completed(self: *const IAsyncAction, result: **AsyncActionCompletedHandler) callconv(.winapi) HRESULT {
        return self.vtable.get_Completed(self, result);
    }
    pub fn GetResults(self: *const IAsyncAction) callconv(.winapi) HRESULT {
        return self.vtable.GetResults(self);
    }
};
pub const IAsyncInfo = extern struct {
    vtable: *const IAsyncInfo_Vtbl,
    pub const Vtbl = IAsyncInfo_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x00000036, .data2 = 0x0000, .data3 = 0x0000, .data4 = .{ 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46 } };
    pub fn QueryInterface(self: *const IAsyncInfo, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IAsyncInfo) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IAsyncInfo) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IAsyncInfo, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn get_Id(self: *const IAsyncInfo, result: *u32) callconv(.winapi) HRESULT {
        return self.vtable.get_Id(self, result);
    }
    pub fn get_Status(self: *const IAsyncInfo, result: *AsyncStatus) callconv(.winapi) HRESULT {
        return self.vtable.get_Status(self, result);
    }
    pub fn get_ErrorCode(self: *const IAsyncInfo, result: *HResult) callconv(.winapi) HRESULT {
        return self.vtable.get_ErrorCode(self, result);
    }
    pub fn Cancel(self: *const IAsyncInfo) callconv(.winapi) HRESULT {
        return self.vtable.Cancel(self);
    }
    pub fn Close(self: *const IAsyncInfo) callconv(.winapi) HRESULT {
        return self.vtable.Close(self);
    }
};
pub const IClosable = extern struct {
    vtable: *const IClosable_Vtbl,
    pub const Vtbl = IClosable_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x30d5a829, .data2 = 0x7fa4, .data3 = 0x4026, .data4 = .{ 0x83, 0xbb, 0xd7, 0x5b, 0xae, 0x4e, 0xa9, 0x9e } };
    pub fn QueryInterface(self: *const IClosable, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IClosable) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IClosable) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IClosable, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn Close(self: *const IClosable) callconv(.winapi) HRESULT {
        return self.vtable.Close(self);
    }
};
pub const IDeferral = extern struct {
    vtable: *const IDeferral_Vtbl,
    pub const Vtbl = IDeferral_Vtbl;
    pub const IID: GUID = .{ .data1 = 0xd6269732, .data2 = 0x3b7f, .data3 = 0x46a7, .data4 = .{ 0xb4, 0x0b, 0x4f, 0xdc, 0xa2, 0xa2, 0xc6, 0x93 } };
    pub fn QueryInterface(self: *const IDeferral, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IDeferral) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IDeferral) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IDeferral, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn Complete(self: *const IDeferral) callconv(.winapi) HRESULT {
        return self.vtable.Complete(self);
    }
};
pub const IDeferralFactory = extern struct {
    vtable: *const IDeferralFactory_Vtbl,
    pub const Vtbl = IDeferralFactory_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x65a1ecc5, .data2 = 0x3fb5, .data3 = 0x4832, .data4 = .{ 0x8c, 0xa9, 0xf0, 0x61, 0xb2, 0x81, 0xd1, 0x3a } };
    pub fn QueryInterface(self: *const IDeferralFactory, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IDeferralFactory) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IDeferralFactory) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IDeferralFactory, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn Create(self: *const IDeferralFactory, p0: *DeferralCompletedHandler, result: **Deferral) callconv(.winapi) HRESULT {
        return self.vtable.Create(self, p0, result);
    }
};
pub const IGetActivationFactory = extern struct {
    vtable: *const IGetActivationFactory_Vtbl,
    pub const Vtbl = IGetActivationFactory_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x4edb8ee2, .data2 = 0x96dd, .data3 = 0x49a7, .data4 = .{ 0x94, 0xf7, 0x46, 0x07, 0xdd, 0xab, 0x8e, 0x3c } };
    pub fn QueryInterface(self: *const IGetActivationFactory, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IGetActivationFactory) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IGetActivationFactory) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IGetActivationFactory, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn GetActivationFactory(self: *const IGetActivationFactory, p0: HSTRING, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.GetActivationFactory(self, p0, result);
    }
    pub fn GetActivationFactoryFromUtf16(self: *const IGetActivationFactory, p0: []const u16, result: *?*const anyopaque) HRESULT {
        var h0 = win_core.Hstring.create(p0) catch return win_core.hresult.E_OUTOFMEMORY;
        defer h0.deinit();
        return self.vtable.GetActivationFactory(self, h0.raw, result);
    }
};
pub const IGuidHelperStatics = extern struct {
    vtable: *const IGuidHelperStatics_Vtbl,
    pub const Vtbl = IGuidHelperStatics_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x59c7966b, .data2 = 0xae52, .data3 = 0x5283, .data4 = .{ 0xad, 0x7f, 0xa1, 0xb9, 0xe9, 0x67, 0x8a, 0xdd } };
    pub fn QueryInterface(self: *const IGuidHelperStatics, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IGuidHelperStatics) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IGuidHelperStatics) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IGuidHelperStatics, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn CreateNewGuid(self: *const IGuidHelperStatics, result: *GUID) callconv(.winapi) HRESULT {
        return self.vtable.CreateNewGuid(self, result);
    }
    pub fn get_Empty(self: *const IGuidHelperStatics, result: *GUID) callconv(.winapi) HRESULT {
        return self.vtable.get_Empty(self, result);
    }
    pub fn Equals(self: *const IGuidHelperStatics, p0: *const GUID, p1: *const GUID, result: *BOOL) callconv(.winapi) HRESULT {
        return self.vtable.Equals(self, p0, p1, result);
    }
};
pub const IMemoryBuffer = extern struct {
    vtable: *const IMemoryBuffer_Vtbl,
    pub const Vtbl = IMemoryBuffer_Vtbl;
    pub const IID: GUID = .{ .data1 = 0xfbc4dd2a, .data2 = 0x245b, .data3 = 0x11e4, .data4 = .{ 0xaf, 0x98, 0x68, 0x94, 0x23, 0x26, 0x0c, 0xf8 } };
    pub fn QueryInterface(self: *const IMemoryBuffer, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IMemoryBuffer) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IMemoryBuffer) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IMemoryBuffer, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn CreateReference(self: *const IMemoryBuffer, result: **IMemoryBufferReference) callconv(.winapi) HRESULT {
        return self.vtable.CreateReference(self, result);
    }
};
pub const IMemoryBufferFactory = extern struct {
    vtable: *const IMemoryBufferFactory_Vtbl,
    pub const Vtbl = IMemoryBufferFactory_Vtbl;
    pub const IID: GUID = .{ .data1 = 0xfbc4dd2b, .data2 = 0x245b, .data3 = 0x11e4, .data4 = .{ 0xaf, 0x98, 0x68, 0x94, 0x23, 0x26, 0x0c, 0xf8 } };
    pub fn QueryInterface(self: *const IMemoryBufferFactory, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IMemoryBufferFactory) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IMemoryBufferFactory) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IMemoryBufferFactory, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn Create(self: *const IMemoryBufferFactory, p0: u32, result: **MemoryBuffer) callconv(.winapi) HRESULT {
        return self.vtable.Create(self, p0, result);
    }
};
pub const IMemoryBufferReference = extern struct {
    vtable: *const IMemoryBufferReference_Vtbl,
    pub const Vtbl = IMemoryBufferReference_Vtbl;
    pub const IID: GUID = .{ .data1 = 0xfbc4dd29, .data2 = 0x245b, .data3 = 0x11e4, .data4 = .{ 0xaf, 0x98, 0x68, 0x94, 0x23, 0x26, 0x0c, 0xf8 } };
    pub fn QueryInterface(self: *const IMemoryBufferReference, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IMemoryBufferReference) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IMemoryBufferReference) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IMemoryBufferReference, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn get_Capacity(self: *const IMemoryBufferReference, result: *u32) callconv(.winapi) HRESULT {
        return self.vtable.get_Capacity(self, result);
    }
    pub fn add_Closed(self: *const IMemoryBufferReference, p0: *TypedEventHandler__G2__Windows_Foundation_IMemoryBufferReference__object, result: *EventRegistrationToken) callconv(.winapi) HRESULT {
        return self.vtable.add_Closed(self, p0, result);
    }
    pub fn remove_Closed(self: *const IMemoryBufferReference, p0: EventRegistrationToken) callconv(.winapi) HRESULT {
        return self.vtable.remove_Closed(self, p0);
    }
    pub fn addClosed(
        self: *const IMemoryBufferReference,
        allocator: std.mem.Allocator,
        invoke: @FieldType(TypedEventHandler__G2__Windows_Foundation_IMemoryBufferReference__object_Vtbl, "Invoke"),
        user_data: ?*anyopaque,
    ) (win_core.hresult.Error || error{OutOfMemory})!EventRegistrationToken {
        const _D = win_core.Delegate(std.meta.Child(@TypeOf(invoke)), TypedEventHandler__G2__Windows_Foundation_IMemoryBufferReference__object.IID);
        const _handler = try _D.create(allocator, invoke, user_data);
        defer _ = _D.release(_handler);
        var _token: EventRegistrationToken = undefined;
        try win_core.hresult.ok(self.add_Closed(@ptrCast(@alignCast(_handler)), &_token));
        return _token;
    }
    pub fn removeClosed(self: *const IMemoryBufferReference, token: EventRegistrationToken) win_core.hresult.Error!void {
        try win_core.hresult.ok(self.remove_Closed(token));
    }
};
pub const IPropertyValue = extern struct {
    vtable: *const IPropertyValue_Vtbl,
    pub const Vtbl = IPropertyValue_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x4bd682dd, .data2 = 0x7554, .data3 = 0x40e9, .data4 = .{ 0x9a, 0x9b, 0x82, 0x65, 0x4e, 0xde, 0x7e, 0x62 } };
    pub fn QueryInterface(self: *const IPropertyValue, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IPropertyValue) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IPropertyValue) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IPropertyValue, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn get_Type(self: *const IPropertyValue, result: *PropertyType) callconv(.winapi) HRESULT {
        return self.vtable.get_Type(self, result);
    }
    pub fn get_IsNumericScalar(self: *const IPropertyValue, result: *BOOL) callconv(.winapi) HRESULT {
        return self.vtable.get_IsNumericScalar(self, result);
    }
    pub fn GetUInt8(self: *const IPropertyValue, result: *u8) callconv(.winapi) HRESULT {
        return self.vtable.GetUInt8(self, result);
    }
    pub fn GetInt16(self: *const IPropertyValue, result: *i16) callconv(.winapi) HRESULT {
        return self.vtable.GetInt16(self, result);
    }
    pub fn GetUInt16(self: *const IPropertyValue, result: *u16) callconv(.winapi) HRESULT {
        return self.vtable.GetUInt16(self, result);
    }
    pub fn GetInt32(self: *const IPropertyValue, result: *i32) callconv(.winapi) HRESULT {
        return self.vtable.GetInt32(self, result);
    }
    pub fn GetUInt32(self: *const IPropertyValue, result: *u32) callconv(.winapi) HRESULT {
        return self.vtable.GetUInt32(self, result);
    }
    pub fn GetInt64(self: *const IPropertyValue, result: *i64) callconv(.winapi) HRESULT {
        return self.vtable.GetInt64(self, result);
    }
    pub fn GetUInt64(self: *const IPropertyValue, result: *u64) callconv(.winapi) HRESULT {
        return self.vtable.GetUInt64(self, result);
    }
    pub fn GetSingle(self: *const IPropertyValue, result: *f32) callconv(.winapi) HRESULT {
        return self.vtable.GetSingle(self, result);
    }
    pub fn GetDouble(self: *const IPropertyValue, result: *f64) callconv(.winapi) HRESULT {
        return self.vtable.GetDouble(self, result);
    }
    pub fn GetChar16(self: *const IPropertyValue, result: *u16) callconv(.winapi) HRESULT {
        return self.vtable.GetChar16(self, result);
    }
    pub fn GetBoolean(self: *const IPropertyValue, result: *BOOL) callconv(.winapi) HRESULT {
        return self.vtable.GetBoolean(self, result);
    }
    pub fn GetString(self: *const IPropertyValue, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.GetString(self, result);
    }
    pub fn GetStringOwned(self: *const IPropertyValue) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.GetString(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn GetGuid(self: *const IPropertyValue, result: *GUID) callconv(.winapi) HRESULT {
        return self.vtable.GetGuid(self, result);
    }
    pub fn GetDateTime(self: *const IPropertyValue, result: *DateTime) callconv(.winapi) HRESULT {
        return self.vtable.GetDateTime(self, result);
    }
    pub fn GetTimeSpan(self: *const IPropertyValue, result: *TimeSpan) callconv(.winapi) HRESULT {
        return self.vtable.GetTimeSpan(self, result);
    }
    pub fn GetPoint(self: *const IPropertyValue, result: *Point) callconv(.winapi) HRESULT {
        return self.vtable.GetPoint(self, result);
    }
    pub fn GetSize(self: *const IPropertyValue, result: *Size) callconv(.winapi) HRESULT {
        return self.vtable.GetSize(self, result);
    }
    pub fn GetRect(self: *const IPropertyValue, result: *Rect) callconv(.winapi) HRESULT {
        return self.vtable.GetRect(self, result);
    }
    pub fn GetUInt8Array(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]u8) callconv(.winapi) HRESULT {
        return self.vtable.GetUInt8Array(self, p0_size, p0_ptr);
    }
    pub fn GetInt16Array(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]i16) callconv(.winapi) HRESULT {
        return self.vtable.GetInt16Array(self, p0_size, p0_ptr);
    }
    pub fn GetUInt16Array(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]u16) callconv(.winapi) HRESULT {
        return self.vtable.GetUInt16Array(self, p0_size, p0_ptr);
    }
    pub fn GetInt32Array(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]i32) callconv(.winapi) HRESULT {
        return self.vtable.GetInt32Array(self, p0_size, p0_ptr);
    }
    pub fn GetUInt32Array(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]u32) callconv(.winapi) HRESULT {
        return self.vtable.GetUInt32Array(self, p0_size, p0_ptr);
    }
    pub fn GetInt64Array(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]i64) callconv(.winapi) HRESULT {
        return self.vtable.GetInt64Array(self, p0_size, p0_ptr);
    }
    pub fn GetUInt64Array(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]u64) callconv(.winapi) HRESULT {
        return self.vtable.GetUInt64Array(self, p0_size, p0_ptr);
    }
    pub fn GetSingleArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]f32) callconv(.winapi) HRESULT {
        return self.vtable.GetSingleArray(self, p0_size, p0_ptr);
    }
    pub fn GetDoubleArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]f64) callconv(.winapi) HRESULT {
        return self.vtable.GetDoubleArray(self, p0_size, p0_ptr);
    }
    pub fn GetChar16Array(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]u16) callconv(.winapi) HRESULT {
        return self.vtable.GetChar16Array(self, p0_size, p0_ptr);
    }
    pub fn GetBooleanArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]BOOL) callconv(.winapi) HRESULT {
        return self.vtable.GetBooleanArray(self, p0_size, p0_ptr);
    }
    pub fn GetStringArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.GetStringArray(self, p0_size, p0_ptr);
    }
    pub fn GetInspectableArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.GetInspectableArray(self, p0_size, p0_ptr);
    }
    pub fn GetGuidArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]GUID) callconv(.winapi) HRESULT {
        return self.vtable.GetGuidArray(self, p0_size, p0_ptr);
    }
    pub fn GetDateTimeArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]DateTime) callconv(.winapi) HRESULT {
        return self.vtable.GetDateTimeArray(self, p0_size, p0_ptr);
    }
    pub fn GetTimeSpanArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]TimeSpan) callconv(.winapi) HRESULT {
        return self.vtable.GetTimeSpanArray(self, p0_size, p0_ptr);
    }
    pub fn GetPointArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]Point) callconv(.winapi) HRESULT {
        return self.vtable.GetPointArray(self, p0_size, p0_ptr);
    }
    pub fn GetSizeArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]Size) callconv(.winapi) HRESULT {
        return self.vtable.GetSizeArray(self, p0_size, p0_ptr);
    }
    pub fn GetRectArray(self: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]Rect) callconv(.winapi) HRESULT {
        return self.vtable.GetRectArray(self, p0_size, p0_ptr);
    }
};
pub const IPropertyValueStatics = extern struct {
    vtable: *const IPropertyValueStatics_Vtbl,
    pub const Vtbl = IPropertyValueStatics_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x629bdbc8, .data2 = 0xd932, .data3 = 0x4ff4, .data4 = .{ 0x96, 0xb9, 0x8d, 0x96, 0xc5, 0xc1, 0xe8, 0x58 } };
    pub fn QueryInterface(self: *const IPropertyValueStatics, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IPropertyValueStatics) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IPropertyValueStatics) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IPropertyValueStatics, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn CreateEmpty(self: *const IPropertyValueStatics, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateEmpty(self, result);
    }
    pub fn CreateUInt8(self: *const IPropertyValueStatics, p0: u8, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateUInt8(self, p0, result);
    }
    pub fn CreateInt16(self: *const IPropertyValueStatics, p0: i16, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateInt16(self, p0, result);
    }
    pub fn CreateUInt16(self: *const IPropertyValueStatics, p0: u16, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateUInt16(self, p0, result);
    }
    pub fn CreateInt32(self: *const IPropertyValueStatics, p0: i32, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateInt32(self, p0, result);
    }
    pub fn CreateUInt32(self: *const IPropertyValueStatics, p0: u32, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateUInt32(self, p0, result);
    }
    pub fn CreateInt64(self: *const IPropertyValueStatics, p0: i64, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateInt64(self, p0, result);
    }
    pub fn CreateUInt64(self: *const IPropertyValueStatics, p0: u64, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateUInt64(self, p0, result);
    }
    pub fn CreateSingle(self: *const IPropertyValueStatics, p0: f32, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateSingle(self, p0, result);
    }
    pub fn CreateDouble(self: *const IPropertyValueStatics, p0: f64, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateDouble(self, p0, result);
    }
    pub fn CreateChar16(self: *const IPropertyValueStatics, p0: u16, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateChar16(self, p0, result);
    }
    pub fn CreateBoolean(self: *const IPropertyValueStatics, p0: BOOL, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateBoolean(self, p0, result);
    }
    pub fn CreateString(self: *const IPropertyValueStatics, p0: HSTRING, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateString(self, p0, result);
    }
    pub fn CreateStringFromUtf16(self: *const IPropertyValueStatics, p0: []const u16, result: *?*const anyopaque) HRESULT {
        var h0 = win_core.Hstring.create(p0) catch return win_core.hresult.E_OUTOFMEMORY;
        defer h0.deinit();
        return self.vtable.CreateString(self, h0.raw, result);
    }
    pub fn CreateInspectable(self: *const IPropertyValueStatics, p0: ?*const anyopaque, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateInspectable(self, p0, result);
    }
    pub fn CreateGuid(self: *const IPropertyValueStatics, p0: GUID, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateGuid(self, p0, result);
    }
    pub fn CreateDateTime(self: *const IPropertyValueStatics, p0: DateTime, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateDateTime(self, p0, result);
    }
    pub fn CreateTimeSpan(self: *const IPropertyValueStatics, p0: TimeSpan, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateTimeSpan(self, p0, result);
    }
    pub fn CreatePoint(self: *const IPropertyValueStatics, p0: Point, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreatePoint(self, p0, result);
    }
    pub fn CreateSize(self: *const IPropertyValueStatics, p0: Size, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateSize(self, p0, result);
    }
    pub fn CreateRect(self: *const IPropertyValueStatics, p0: Rect, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateRect(self, p0, result);
    }
    pub fn CreateUInt8Array(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const u8, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateUInt8Array(self, p0_size, p0_ptr, result);
    }
    pub fn CreateInt16Array(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const i16, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateInt16Array(self, p0_size, p0_ptr, result);
    }
    pub fn CreateUInt16Array(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const u16, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateUInt16Array(self, p0_size, p0_ptr, result);
    }
    pub fn CreateInt32Array(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const i32, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateInt32Array(self, p0_size, p0_ptr, result);
    }
    pub fn CreateUInt32Array(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const u32, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateUInt32Array(self, p0_size, p0_ptr, result);
    }
    pub fn CreateInt64Array(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const i64, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateInt64Array(self, p0_size, p0_ptr, result);
    }
    pub fn CreateUInt64Array(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const u64, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateUInt64Array(self, p0_size, p0_ptr, result);
    }
    pub fn CreateSingleArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const f32, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateSingleArray(self, p0_size, p0_ptr, result);
    }
    pub fn CreateDoubleArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const f64, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateDoubleArray(self, p0_size, p0_ptr, result);
    }
    pub fn CreateChar16Array(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const u16, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateChar16Array(self, p0_size, p0_ptr, result);
    }
    pub fn CreateBooleanArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const BOOL, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateBooleanArray(self, p0_size, p0_ptr, result);
    }
    pub fn CreateStringArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const HSTRING, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateStringArray(self, p0_size, p0_ptr, result);
    }
    pub fn CreateInspectableArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const ?*const anyopaque, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateInspectableArray(self, p0_size, p0_ptr, result);
    }
    pub fn CreateGuidArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const GUID, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateGuidArray(self, p0_size, p0_ptr, result);
    }
    pub fn CreateDateTimeArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const DateTime, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateDateTimeArray(self, p0_size, p0_ptr, result);
    }
    pub fn CreateTimeSpanArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const TimeSpan, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateTimeSpanArray(self, p0_size, p0_ptr, result);
    }
    pub fn CreatePointArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const Point, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreatePointArray(self, p0_size, p0_ptr, result);
    }
    pub fn CreateSizeArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const Size, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateSizeArray(self, p0_size, p0_ptr, result);
    }
    pub fn CreateRectArray(self: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const Rect, result: *?*const anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.CreateRectArray(self, p0_size, p0_ptr, result);
    }
};
pub const IStringable = extern struct {
    vtable: *const IStringable_Vtbl,
    pub const Vtbl = IStringable_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x96369f54, .data2 = 0x8eb6, .data3 = 0x48f0, .data4 = .{ 0xab, 0xce, 0xc1, 0xb2, 0x11, 0xe6, 0x27, 0xc3 } };
    pub fn QueryInterface(self: *const IStringable, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IStringable) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IStringable) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IStringable, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn ToString(self: *const IStringable, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.ToString(self, result);
    }
    pub fn ToStringOwned(self: *const IStringable) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.ToString(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
};
pub const IUriEscapeStatics = extern struct {
    vtable: *const IUriEscapeStatics_Vtbl,
    pub const Vtbl = IUriEscapeStatics_Vtbl;
    pub const IID: GUID = .{ .data1 = 0xc1d432ba, .data2 = 0xc824, .data3 = 0x4452, .data4 = .{ 0xa7, 0xfd, 0x51, 0x2b, 0xc3, 0xbb, 0xe9, 0xa1 } };
    pub fn QueryInterface(self: *const IUriEscapeStatics, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IUriEscapeStatics) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IUriEscapeStatics) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IUriEscapeStatics, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn UnescapeComponent(self: *const IUriEscapeStatics, p0: HSTRING, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.UnescapeComponent(self, p0, result);
    }
    pub fn UnescapeComponentFromUtf16(self: *const IUriEscapeStatics, p0: []const u16, result: *HSTRING) HRESULT {
        var h0 = win_core.Hstring.create(p0) catch return win_core.hresult.E_OUTOFMEMORY;
        defer h0.deinit();
        return self.vtable.UnescapeComponent(self, h0.raw, result);
    }
    pub fn UnescapeComponentOwned(self: *const IUriEscapeStatics, p0: HSTRING) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.UnescapeComponent(self, p0, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn UnescapeComponentOwnedFromUtf16(self: *const IUriEscapeStatics, p0: []const u16) !win_core.Hstring {
        var h0 = win_core.Hstring.create(p0) catch return error.OutOfMemory;
        defer h0.deinit();
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.UnescapeComponent(self, h0.raw, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn EscapeComponent(self: *const IUriEscapeStatics, p0: HSTRING, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.EscapeComponent(self, p0, result);
    }
    pub fn EscapeComponentFromUtf16(self: *const IUriEscapeStatics, p0: []const u16, result: *HSTRING) HRESULT {
        var h0 = win_core.Hstring.create(p0) catch return win_core.hresult.E_OUTOFMEMORY;
        defer h0.deinit();
        return self.vtable.EscapeComponent(self, h0.raw, result);
    }
    pub fn EscapeComponentOwned(self: *const IUriEscapeStatics, p0: HSTRING) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.EscapeComponent(self, p0, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn EscapeComponentOwnedFromUtf16(self: *const IUriEscapeStatics, p0: []const u16) !win_core.Hstring {
        var h0 = win_core.Hstring.create(p0) catch return error.OutOfMemory;
        defer h0.deinit();
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.EscapeComponent(self, h0.raw, &r));
        return win_core.Hstring.fromRaw(r);
    }
};
pub const IUriRuntimeClass = extern struct {
    vtable: *const IUriRuntimeClass_Vtbl,
    pub const Vtbl = IUriRuntimeClass_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x9e365e57, .data2 = 0x48b2, .data3 = 0x4160, .data4 = .{ 0x95, 0x6f, 0xc7, 0x38, 0x51, 0x20, 0xbb, 0xfc } };
    pub fn QueryInterface(self: *const IUriRuntimeClass, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IUriRuntimeClass) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IUriRuntimeClass) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IUriRuntimeClass, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn get_AbsoluteUri(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_AbsoluteUri(self, result);
    }
    pub fn get_AbsoluteUriOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_AbsoluteUri(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_DisplayUri(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_DisplayUri(self, result);
    }
    pub fn get_DisplayUriOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_DisplayUri(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_Domain(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_Domain(self, result);
    }
    pub fn get_DomainOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_Domain(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_Extension(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_Extension(self, result);
    }
    pub fn get_ExtensionOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_Extension(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_Fragment(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_Fragment(self, result);
    }
    pub fn get_FragmentOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_Fragment(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_Host(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_Host(self, result);
    }
    pub fn get_HostOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_Host(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_Password(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_Password(self, result);
    }
    pub fn get_PasswordOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_Password(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_Path(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_Path(self, result);
    }
    pub fn get_PathOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_Path(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_Query(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_Query(self, result);
    }
    pub fn get_QueryOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_Query(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_QueryParsed(self: *const IUriRuntimeClass, result: **WwwFormUrlDecoder) callconv(.winapi) HRESULT {
        return self.vtable.get_QueryParsed(self, result);
    }
    pub fn get_RawUri(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_RawUri(self, result);
    }
    pub fn get_RawUriOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_RawUri(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_SchemeName(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_SchemeName(self, result);
    }
    pub fn get_SchemeNameOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_SchemeName(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_UserName(self: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_UserName(self, result);
    }
    pub fn get_UserNameOwned(self: *const IUriRuntimeClass) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_UserName(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_Port(self: *const IUriRuntimeClass, result: *i32) callconv(.winapi) HRESULT {
        return self.vtable.get_Port(self, result);
    }
    pub fn get_Suspicious(self: *const IUriRuntimeClass, result: *BOOL) callconv(.winapi) HRESULT {
        return self.vtable.get_Suspicious(self, result);
    }
    pub fn Equals(self: *const IUriRuntimeClass, p0: *Uri, result: *BOOL) callconv(.winapi) HRESULT {
        return self.vtable.Equals(self, p0, result);
    }
    pub fn CombineUri(self: *const IUriRuntimeClass, p0: HSTRING, result: **Uri) callconv(.winapi) HRESULT {
        return self.vtable.CombineUri(self, p0, result);
    }
    pub fn CombineUriFromUtf16(self: *const IUriRuntimeClass, p0: []const u16, result: **Uri) HRESULT {
        var h0 = win_core.Hstring.create(p0) catch return win_core.hresult.E_OUTOFMEMORY;
        defer h0.deinit();
        return self.vtable.CombineUri(self, h0.raw, result);
    }
};
pub const IUriRuntimeClassFactory = extern struct {
    vtable: *const IUriRuntimeClassFactory_Vtbl,
    pub const Vtbl = IUriRuntimeClassFactory_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x44a9796f, .data2 = 0x723e, .data3 = 0x4fdf, .data4 = .{ 0xa2, 0x18, 0x03, 0x3e, 0x75, 0xb0, 0xc0, 0x84 } };
    pub fn QueryInterface(self: *const IUriRuntimeClassFactory, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IUriRuntimeClassFactory) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IUriRuntimeClassFactory) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IUriRuntimeClassFactory, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn CreateUri(self: *const IUriRuntimeClassFactory, p0: HSTRING, result: **Uri) callconv(.winapi) HRESULT {
        return self.vtable.CreateUri(self, p0, result);
    }
    pub fn CreateUriFromUtf16(self: *const IUriRuntimeClassFactory, p0: []const u16, result: **Uri) HRESULT {
        var h0 = win_core.Hstring.create(p0) catch return win_core.hresult.E_OUTOFMEMORY;
        defer h0.deinit();
        return self.vtable.CreateUri(self, h0.raw, result);
    }
    pub fn CreateWithRelativeUri(self: *const IUriRuntimeClassFactory, p0: HSTRING, p1: HSTRING, result: **Uri) callconv(.winapi) HRESULT {
        return self.vtable.CreateWithRelativeUri(self, p0, p1, result);
    }
    pub fn CreateWithRelativeUriFromUtf16(self: *const IUriRuntimeClassFactory, p0: []const u16, p1: []const u16, result: **Uri) HRESULT {
        var h0 = win_core.Hstring.create(p0) catch return win_core.hresult.E_OUTOFMEMORY;
        defer h0.deinit();
        var h1 = win_core.Hstring.create(p1) catch return win_core.hresult.E_OUTOFMEMORY;
        defer h1.deinit();
        return self.vtable.CreateWithRelativeUri(self, h0.raw, h1.raw, result);
    }
};
pub const IUriRuntimeClassWithAbsoluteCanonicalUri = extern struct {
    vtable: *const IUriRuntimeClassWithAbsoluteCanonicalUri_Vtbl,
    pub const Vtbl = IUriRuntimeClassWithAbsoluteCanonicalUri_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x758d9661, .data2 = 0x221c, .data3 = 0x480f, .data4 = .{ 0xa3, 0x39, 0x50, 0x65, 0x66, 0x73, 0xf4, 0x6f } };
    pub fn QueryInterface(self: *const IUriRuntimeClassWithAbsoluteCanonicalUri, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IUriRuntimeClassWithAbsoluteCanonicalUri) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IUriRuntimeClassWithAbsoluteCanonicalUri) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IUriRuntimeClassWithAbsoluteCanonicalUri, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn get_AbsoluteCanonicalUri(self: *const IUriRuntimeClassWithAbsoluteCanonicalUri, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_AbsoluteCanonicalUri(self, result);
    }
    pub fn get_AbsoluteCanonicalUriOwned(self: *const IUriRuntimeClassWithAbsoluteCanonicalUri) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_AbsoluteCanonicalUri(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_DisplayIri(self: *const IUriRuntimeClassWithAbsoluteCanonicalUri, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_DisplayIri(self, result);
    }
    pub fn get_DisplayIriOwned(self: *const IUriRuntimeClassWithAbsoluteCanonicalUri) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_DisplayIri(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
};
pub const IWwwFormUrlDecoderEntry = extern struct {
    vtable: *const IWwwFormUrlDecoderEntry_Vtbl,
    pub const Vtbl = IWwwFormUrlDecoderEntry_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x125e7431, .data2 = 0xf678, .data3 = 0x4e8e, .data4 = .{ 0xb6, 0x70, 0x20, 0xa9, 0xb0, 0x6c, 0x51, 0x2d } };
    pub fn QueryInterface(self: *const IWwwFormUrlDecoderEntry, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IWwwFormUrlDecoderEntry) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IWwwFormUrlDecoderEntry) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IWwwFormUrlDecoderEntry, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn get_Name(self: *const IWwwFormUrlDecoderEntry, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_Name(self, result);
    }
    pub fn get_NameOwned(self: *const IWwwFormUrlDecoderEntry) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_Name(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn get_Value(self: *const IWwwFormUrlDecoderEntry, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.get_Value(self, result);
    }
    pub fn get_ValueOwned(self: *const IWwwFormUrlDecoderEntry) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.get_Value(self, &r));
        return win_core.Hstring.fromRaw(r);
    }
};
pub const IWwwFormUrlDecoderRuntimeClass = extern struct {
    vtable: *const IWwwFormUrlDecoderRuntimeClass_Vtbl,
    pub const Vtbl = IWwwFormUrlDecoderRuntimeClass_Vtbl;
    pub const IID: GUID = .{ .data1 = 0xd45a0451, .data2 = 0xf225, .data3 = 0x4542, .data4 = .{ 0x92, 0x96, 0x0e, 0x1d, 0xf5, 0xd2, 0x54, 0xdf } };
    pub fn QueryInterface(self: *const IWwwFormUrlDecoderRuntimeClass, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IWwwFormUrlDecoderRuntimeClass) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IWwwFormUrlDecoderRuntimeClass) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IWwwFormUrlDecoderRuntimeClass, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn GetFirstValueByName(self: *const IWwwFormUrlDecoderRuntimeClass, p0: HSTRING, result: *HSTRING) callconv(.winapi) HRESULT {
        return self.vtable.GetFirstValueByName(self, p0, result);
    }
    pub fn GetFirstValueByNameFromUtf16(self: *const IWwwFormUrlDecoderRuntimeClass, p0: []const u16, result: *HSTRING) HRESULT {
        var h0 = win_core.Hstring.create(p0) catch return win_core.hresult.E_OUTOFMEMORY;
        defer h0.deinit();
        return self.vtable.GetFirstValueByName(self, h0.raw, result);
    }
    pub fn GetFirstValueByNameOwned(self: *const IWwwFormUrlDecoderRuntimeClass, p0: HSTRING) !win_core.Hstring {
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.GetFirstValueByName(self, p0, &r));
        return win_core.Hstring.fromRaw(r);
    }
    pub fn GetFirstValueByNameOwnedFromUtf16(self: *const IWwwFormUrlDecoderRuntimeClass, p0: []const u16) !win_core.Hstring {
        var h0 = win_core.Hstring.create(p0) catch return error.OutOfMemory;
        defer h0.deinit();
        var r: HSTRING = null;
        try win_core.hresult.ok(self.vtable.GetFirstValueByName(self, h0.raw, &r));
        return win_core.Hstring.fromRaw(r);
    }
};
pub const IWwwFormUrlDecoderRuntimeClassFactory = extern struct {
    vtable: *const IWwwFormUrlDecoderRuntimeClassFactory_Vtbl,
    pub const Vtbl = IWwwFormUrlDecoderRuntimeClassFactory_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x5b8c6b3d, .data2 = 0x24ae, .data3 = 0x41b5, .data4 = .{ 0xa1, 0xbf, 0xf0, 0xc3, 0xd5, 0x44, 0x84, 0x5b } };
    pub fn QueryInterface(self: *const IWwwFormUrlDecoderRuntimeClassFactory, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {
        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
    }
    pub fn AddRef(self: *const IWwwFormUrlDecoderRuntimeClassFactory) callconv(.winapi) u32 {
        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
    }
    pub fn Release(self: *const IWwwFormUrlDecoderRuntimeClassFactory) callconv(.winapi) u32 {
        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
    }
    pub fn cast(self: *const IWwwFormUrlDecoderRuntimeClassFactory, comptime T: type) ?*const T {
        var out: ?*anyopaque = null;
        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        return @ptrCast(@alignCast(out));
    }
    pub fn CreateWwwFormUrlDecoder(self: *const IWwwFormUrlDecoderRuntimeClassFactory, p0: HSTRING, result: **WwwFormUrlDecoder) callconv(.winapi) HRESULT {
        return self.vtable.CreateWwwFormUrlDecoder(self, p0, result);
    }
    pub fn CreateWwwFormUrlDecoderFromUtf16(self: *const IWwwFormUrlDecoderRuntimeClassFactory, p0: []const u16, result: **WwwFormUrlDecoder) HRESULT {
        var h0 = win_core.Hstring.create(p0) catch return win_core.hresult.E_OUTOFMEMORY;
        defer h0.deinit();
        return self.vtable.CreateWwwFormUrlDecoder(self, h0.raw, result);
    }
};
pub const AsyncActionCompletedHandler = opaque {};
pub const DeferralCompletedHandler = opaque {};
pub const Deferral = extern struct {
    vtable: *const IDeferral_Vtbl,
    pub const NAME: []const u8 = "Windows.Foundation.Deferral";
    pub const NAME_W: [27]u16 = .{ 87, 105, 110, 100, 111, 119, 115, 46, 70, 111, 117, 110, 100, 97, 116, 105, 111, 110, 46, 68, 101, 102, 101, 114, 114, 97, 108 };
    pub const Factory = IDeferralFactory;
    pub fn factory() !win_core.Com(Factory.Vtbl) {
        return win_core.activationFactory(Factory.Vtbl, &Factory.IID, &NAME_W);
    }
};
pub const GuidHelper = extern struct {
    vtable: *const anyopaque,
    pub const NAME: []const u8 = "Windows.Foundation.GuidHelper";
    pub const NAME_W: [29]u16 = .{ 87, 105, 110, 100, 111, 119, 115, 46, 70, 111, 117, 110, 100, 97, 116, 105, 111, 110, 46, 71, 117, 105, 100, 72, 101, 108, 112, 101, 114 };
    pub const Statics = IGuidHelperStatics;
    pub fn statics() !win_core.Com(Statics.Vtbl) {
        return win_core.activationFactory(Statics.Vtbl, &Statics.IID, &NAME_W);
    }
};
pub const MemoryBuffer = extern struct {
    vtable: *const IMemoryBuffer_Vtbl,
    pub const NAME: []const u8 = "Windows.Foundation.MemoryBuffer";
    pub const NAME_W: [31]u16 = .{ 87, 105, 110, 100, 111, 119, 115, 46, 70, 111, 117, 110, 100, 97, 116, 105, 111, 110, 46, 77, 101, 109, 111, 114, 121, 66, 117, 102, 102, 101, 114 };
    pub const Factory = IMemoryBufferFactory;
    pub fn factory() !win_core.Com(Factory.Vtbl) {
        return win_core.activationFactory(Factory.Vtbl, &Factory.IID, &NAME_W);
    }
};
pub const PropertyValue = extern struct {
    vtable: *const anyopaque,
    pub const NAME: []const u8 = "Windows.Foundation.PropertyValue";
    pub const NAME_W: [32]u16 = .{ 87, 105, 110, 100, 111, 119, 115, 46, 70, 111, 117, 110, 100, 97, 116, 105, 111, 110, 46, 80, 114, 111, 112, 101, 114, 116, 121, 86, 97, 108, 117, 101 };
    pub const Statics = IPropertyValueStatics;
    pub fn statics() !win_core.Com(Statics.Vtbl) {
        return win_core.activationFactory(Statics.Vtbl, &Statics.IID, &NAME_W);
    }
};
pub const Uri = extern struct {
    vtable: *const IUriRuntimeClass_Vtbl,
    pub const NAME: []const u8 = "Windows.Foundation.Uri";
    pub const NAME_W: [22]u16 = .{ 87, 105, 110, 100, 111, 119, 115, 46, 70, 111, 117, 110, 100, 97, 116, 105, 111, 110, 46, 85, 114, 105 };
    pub const Factory = IUriRuntimeClassFactory;
    pub fn factory() !win_core.Com(Factory.Vtbl) {
        return win_core.activationFactory(Factory.Vtbl, &Factory.IID, &NAME_W);
    }
    pub const Statics = IUriEscapeStatics;
    pub fn statics() !win_core.Com(Statics.Vtbl) {
        return win_core.activationFactory(Statics.Vtbl, &Statics.IID, &NAME_W);
    }
};
pub const WwwFormUrlDecoder = extern struct {
    vtable: *const IWwwFormUrlDecoderRuntimeClass_Vtbl,
    pub const NAME: []const u8 = "Windows.Foundation.WwwFormUrlDecoder";
    pub const NAME_W: [36]u16 = .{ 87, 105, 110, 100, 111, 119, 115, 46, 70, 111, 117, 110, 100, 97, 116, 105, 111, 110, 46, 87, 119, 119, 70, 111, 114, 109, 85, 114, 108, 68, 101, 99, 111, 100, 101, 114 };
    pub const Factory = IWwwFormUrlDecoderRuntimeClassFactory;
    pub fn factory() !win_core.Com(Factory.Vtbl) {
        return win_core.activationFactory(Factory.Vtbl, &Factory.IID, &NAME_W);
    }
};
pub const WwwFormUrlDecoderEntry = extern struct {
    vtable: *const IWwwFormUrlDecoderEntry_Vtbl,
    pub const NAME: []const u8 = "Windows.Foundation.WwwFormUrlDecoderEntry";
    pub const NAME_W: [41]u16 = .{ 87, 105, 110, 100, 111, 119, 115, 46, 70, 111, 117, 110, 100, 97, 116, 105, 111, 110, 46, 87, 119, 119, 70, 111, 114, 109, 85, 114, 108, 68, 101, 99, 111, 100, 101, 114, 69, 110, 116, 114, 121 };
};
pub const IAsyncAction_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    put_Completed: *const fn (this: *const IAsyncAction, p0: *AsyncActionCompletedHandler) callconv(.winapi) HRESULT,
    get_Completed: *const fn (this: *const IAsyncAction, result: **AsyncActionCompletedHandler) callconv(.winapi) HRESULT,
    GetResults: *const fn (this: *const IAsyncAction) callconv(.winapi) HRESULT,
};
pub const IAsyncInfo_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Id: *const fn (this: *const IAsyncInfo, result: *u32) callconv(.winapi) HRESULT,
    get_Status: *const fn (this: *const IAsyncInfo, result: *AsyncStatus) callconv(.winapi) HRESULT,
    get_ErrorCode: *const fn (this: *const IAsyncInfo, result: *HResult) callconv(.winapi) HRESULT,
    Cancel: *const fn (this: *const IAsyncInfo) callconv(.winapi) HRESULT,
    Close: *const fn (this: *const IAsyncInfo) callconv(.winapi) HRESULT,
};
pub const IClosable_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    Close: *const fn (this: *const IClosable) callconv(.winapi) HRESULT,
};
pub const IDeferral_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    Complete: *const fn (this: *const IDeferral) callconv(.winapi) HRESULT,
};
pub const IDeferralFactory_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    Create: *const fn (this: *const IDeferralFactory, p0: *DeferralCompletedHandler, result: **Deferral) callconv(.winapi) HRESULT,
};
pub const IGetActivationFactory_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    GetActivationFactory: *const fn (this: *const IGetActivationFactory, p0: HSTRING, result: *?*const anyopaque) callconv(.winapi) HRESULT,
};
pub const IGuidHelperStatics_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    CreateNewGuid: *const fn (this: *const IGuidHelperStatics, result: *GUID) callconv(.winapi) HRESULT,
    get_Empty: *const fn (this: *const IGuidHelperStatics, result: *GUID) callconv(.winapi) HRESULT,
    Equals: *const fn (this: *const IGuidHelperStatics, p0: *const GUID, p1: *const GUID, result: *BOOL) callconv(.winapi) HRESULT,
};
pub const IMemoryBuffer_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    CreateReference: *const fn (this: *const IMemoryBuffer, result: **IMemoryBufferReference) callconv(.winapi) HRESULT,
};
pub const IMemoryBufferFactory_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    Create: *const fn (this: *const IMemoryBufferFactory, p0: u32, result: **MemoryBuffer) callconv(.winapi) HRESULT,
};
pub const IMemoryBufferReference_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Capacity: *const fn (this: *const IMemoryBufferReference, result: *u32) callconv(.winapi) HRESULT,
    add_Closed: *const fn (this: *const IMemoryBufferReference, p0: *TypedEventHandler__G2__Windows_Foundation_IMemoryBufferReference__object, result: *EventRegistrationToken) callconv(.winapi) HRESULT,
    remove_Closed: *const fn (this: *const IMemoryBufferReference, p0: EventRegistrationToken) callconv(.winapi) HRESULT,
};
pub const IPropertyValue_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Type: *const fn (this: *const IPropertyValue, result: *PropertyType) callconv(.winapi) HRESULT,
    get_IsNumericScalar: *const fn (this: *const IPropertyValue, result: *BOOL) callconv(.winapi) HRESULT,
    GetUInt8: *const fn (this: *const IPropertyValue, result: *u8) callconv(.winapi) HRESULT,
    GetInt16: *const fn (this: *const IPropertyValue, result: *i16) callconv(.winapi) HRESULT,
    GetUInt16: *const fn (this: *const IPropertyValue, result: *u16) callconv(.winapi) HRESULT,
    GetInt32: *const fn (this: *const IPropertyValue, result: *i32) callconv(.winapi) HRESULT,
    GetUInt32: *const fn (this: *const IPropertyValue, result: *u32) callconv(.winapi) HRESULT,
    GetInt64: *const fn (this: *const IPropertyValue, result: *i64) callconv(.winapi) HRESULT,
    GetUInt64: *const fn (this: *const IPropertyValue, result: *u64) callconv(.winapi) HRESULT,
    GetSingle: *const fn (this: *const IPropertyValue, result: *f32) callconv(.winapi) HRESULT,
    GetDouble: *const fn (this: *const IPropertyValue, result: *f64) callconv(.winapi) HRESULT,
    GetChar16: *const fn (this: *const IPropertyValue, result: *u16) callconv(.winapi) HRESULT,
    GetBoolean: *const fn (this: *const IPropertyValue, result: *BOOL) callconv(.winapi) HRESULT,
    GetString: *const fn (this: *const IPropertyValue, result: *HSTRING) callconv(.winapi) HRESULT,
    GetGuid: *const fn (this: *const IPropertyValue, result: *GUID) callconv(.winapi) HRESULT,
    GetDateTime: *const fn (this: *const IPropertyValue, result: *DateTime) callconv(.winapi) HRESULT,
    GetTimeSpan: *const fn (this: *const IPropertyValue, result: *TimeSpan) callconv(.winapi) HRESULT,
    GetPoint: *const fn (this: *const IPropertyValue, result: *Point) callconv(.winapi) HRESULT,
    GetSize: *const fn (this: *const IPropertyValue, result: *Size) callconv(.winapi) HRESULT,
    GetRect: *const fn (this: *const IPropertyValue, result: *Rect) callconv(.winapi) HRESULT,
    GetUInt8Array: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]u8) callconv(.winapi) HRESULT,
    GetInt16Array: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]i16) callconv(.winapi) HRESULT,
    GetUInt16Array: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]u16) callconv(.winapi) HRESULT,
    GetInt32Array: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]i32) callconv(.winapi) HRESULT,
    GetUInt32Array: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]u32) callconv(.winapi) HRESULT,
    GetInt64Array: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]i64) callconv(.winapi) HRESULT,
    GetUInt64Array: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]u64) callconv(.winapi) HRESULT,
    GetSingleArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]f32) callconv(.winapi) HRESULT,
    GetDoubleArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]f64) callconv(.winapi) HRESULT,
    GetChar16Array: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]u16) callconv(.winapi) HRESULT,
    GetBooleanArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]BOOL) callconv(.winapi) HRESULT,
    GetStringArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]HSTRING) callconv(.winapi) HRESULT,
    GetInspectableArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]?*const anyopaque) callconv(.winapi) HRESULT,
    GetGuidArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]GUID) callconv(.winapi) HRESULT,
    GetDateTimeArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]DateTime) callconv(.winapi) HRESULT,
    GetTimeSpanArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]TimeSpan) callconv(.winapi) HRESULT,
    GetPointArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]Point) callconv(.winapi) HRESULT,
    GetSizeArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]Size) callconv(.winapi) HRESULT,
    GetRectArray: *const fn (this: *const IPropertyValue, p0_size: *u32, p0_ptr: *[*]Rect) callconv(.winapi) HRESULT,
};
pub const IPropertyValueStatics_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    CreateEmpty: *const fn (this: *const IPropertyValueStatics, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateUInt8: *const fn (this: *const IPropertyValueStatics, p0: u8, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateInt16: *const fn (this: *const IPropertyValueStatics, p0: i16, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateUInt16: *const fn (this: *const IPropertyValueStatics, p0: u16, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateInt32: *const fn (this: *const IPropertyValueStatics, p0: i32, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateUInt32: *const fn (this: *const IPropertyValueStatics, p0: u32, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateInt64: *const fn (this: *const IPropertyValueStatics, p0: i64, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateUInt64: *const fn (this: *const IPropertyValueStatics, p0: u64, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateSingle: *const fn (this: *const IPropertyValueStatics, p0: f32, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateDouble: *const fn (this: *const IPropertyValueStatics, p0: f64, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateChar16: *const fn (this: *const IPropertyValueStatics, p0: u16, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateBoolean: *const fn (this: *const IPropertyValueStatics, p0: BOOL, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateString: *const fn (this: *const IPropertyValueStatics, p0: HSTRING, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateInspectable: *const fn (this: *const IPropertyValueStatics, p0: ?*const anyopaque, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateGuid: *const fn (this: *const IPropertyValueStatics, p0: GUID, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateDateTime: *const fn (this: *const IPropertyValueStatics, p0: DateTime, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateTimeSpan: *const fn (this: *const IPropertyValueStatics, p0: TimeSpan, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreatePoint: *const fn (this: *const IPropertyValueStatics, p0: Point, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateSize: *const fn (this: *const IPropertyValueStatics, p0: Size, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateRect: *const fn (this: *const IPropertyValueStatics, p0: Rect, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateUInt8Array: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const u8, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateInt16Array: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const i16, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateUInt16Array: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const u16, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateInt32Array: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const i32, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateUInt32Array: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const u32, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateInt64Array: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const i64, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateUInt64Array: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const u64, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateSingleArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const f32, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateDoubleArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const f64, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateChar16Array: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const u16, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateBooleanArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const BOOL, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateStringArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const HSTRING, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateInspectableArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const ?*const anyopaque, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateGuidArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const GUID, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateDateTimeArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const DateTime, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateTimeSpanArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const TimeSpan, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreatePointArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const Point, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateSizeArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const Size, result: *?*const anyopaque) callconv(.winapi) HRESULT,
    CreateRectArray: *const fn (this: *const IPropertyValueStatics, p0_size: u32, p0_ptr: [*]const Rect, result: *?*const anyopaque) callconv(.winapi) HRESULT,
};
pub const IStringable_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    ToString: *const fn (this: *const IStringable, result: *HSTRING) callconv(.winapi) HRESULT,
};
pub const IUriEscapeStatics_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    UnescapeComponent: *const fn (this: *const IUriEscapeStatics, p0: HSTRING, result: *HSTRING) callconv(.winapi) HRESULT,
    EscapeComponent: *const fn (this: *const IUriEscapeStatics, p0: HSTRING, result: *HSTRING) callconv(.winapi) HRESULT,
};
pub const IUriRuntimeClass_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_AbsoluteUri: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_DisplayUri: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_Domain: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_Extension: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_Fragment: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_Host: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_Password: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_Path: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_Query: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_QueryParsed: *const fn (this: *const IUriRuntimeClass, result: **WwwFormUrlDecoder) callconv(.winapi) HRESULT,
    get_RawUri: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_SchemeName: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_UserName: *const fn (this: *const IUriRuntimeClass, result: *HSTRING) callconv(.winapi) HRESULT,
    get_Port: *const fn (this: *const IUriRuntimeClass, result: *i32) callconv(.winapi) HRESULT,
    get_Suspicious: *const fn (this: *const IUriRuntimeClass, result: *BOOL) callconv(.winapi) HRESULT,
    Equals: *const fn (this: *const IUriRuntimeClass, p0: *Uri, result: *BOOL) callconv(.winapi) HRESULT,
    CombineUri: *const fn (this: *const IUriRuntimeClass, p0: HSTRING, result: **Uri) callconv(.winapi) HRESULT,
};
pub const IUriRuntimeClassFactory_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    CreateUri: *const fn (this: *const IUriRuntimeClassFactory, p0: HSTRING, result: **Uri) callconv(.winapi) HRESULT,
    CreateWithRelativeUri: *const fn (this: *const IUriRuntimeClassFactory, p0: HSTRING, p1: HSTRING, result: **Uri) callconv(.winapi) HRESULT,
};
pub const IUriRuntimeClassWithAbsoluteCanonicalUri_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_AbsoluteCanonicalUri: *const fn (this: *const IUriRuntimeClassWithAbsoluteCanonicalUri, result: *HSTRING) callconv(.winapi) HRESULT,
    get_DisplayIri: *const fn (this: *const IUriRuntimeClassWithAbsoluteCanonicalUri, result: *HSTRING) callconv(.winapi) HRESULT,
};
pub const IWwwFormUrlDecoderEntry_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Name: *const fn (this: *const IWwwFormUrlDecoderEntry, result: *HSTRING) callconv(.winapi) HRESULT,
    get_Value: *const fn (this: *const IWwwFormUrlDecoderEntry, result: *HSTRING) callconv(.winapi) HRESULT,
};
pub const IWwwFormUrlDecoderRuntimeClass_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    GetFirstValueByName: *const fn (this: *const IWwwFormUrlDecoderRuntimeClass, p0: HSTRING, result: *HSTRING) callconv(.winapi) HRESULT,
};
pub const IWwwFormUrlDecoderRuntimeClassFactory_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    CreateWwwFormUrlDecoder: *const fn (this: *const IWwwFormUrlDecoderRuntimeClassFactory, p0: HSTRING, result: **WwwFormUrlDecoder) callconv(.winapi) HRESULT,
};
pub const TypedEventHandler__G2__Windows_Foundation_IMemoryBufferReference__object_Vtbl = extern struct {
    base: IUnknown_Vtbl,
    Invoke: *const fn (this: *const TypedEventHandler__G2__Windows_Foundation_IMemoryBufferReference__object, p0: *IMemoryBufferReference, p1: ?*const anyopaque) callconv(.winapi) HRESULT,
};
pub const TypedEventHandler__G2__Windows_Foundation_IMemoryBufferReference__object = extern struct {
    vtable: *const TypedEventHandler__G2__Windows_Foundation_IMemoryBufferReference__object_Vtbl,
    pub const Vtbl = TypedEventHandler__G2__Windows_Foundation_IMemoryBufferReference__object_Vtbl;
    pub const IID: GUID = .{ .data1 = 0xf4637d4a, .data2 = 0x0760, .data3 = 0x5431, .data4 = .{ 0xbf, 0xc0, 0x24, 0xeb, 0x1d, 0x4f, 0x6c, 0x4f } };
};
pub const IReference__G1__BOOL_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Value: *const fn (this: *const IReference__G1__BOOL, result: *BOOL) callconv(.winapi) HRESULT,
};
pub const IReference__G1__BOOL = extern struct {
    vtable: *const IReference__G1__BOOL_Vtbl,
    pub const Vtbl = IReference__G1__BOOL_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x3c00fd60, .data2 = 0x2950, .data3 = 0x5939, .data4 = .{ 0xa2, 0x1a, 0x2d, 0x12, 0xc5, 0xa0, 0x1b, 0x8a } };
};
pub const IReference__G1__u8_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Value: *const fn (this: *const IReference__G1__u8, result: *u8) callconv(.winapi) HRESULT,
};
pub const IReference__G1__u8 = extern struct {
    vtable: *const IReference__G1__u8_Vtbl,
    pub const Vtbl = IReference__G1__u8_Vtbl;
    pub const IID: GUID = .{ .data1 = 0xe5198cc8, .data2 = 0x2873, .data3 = 0x55f5, .data4 = .{ 0xb0, 0xa1, 0x84, 0xff, 0x9e, 0x4a, 0xad, 0x62 } };
};
pub const IReference__G1__i16_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Value: *const fn (this: *const IReference__G1__i16, result: *i16) callconv(.winapi) HRESULT,
};
pub const IReference__G1__i16 = extern struct {
    vtable: *const IReference__G1__i16_Vtbl,
    pub const Vtbl = IReference__G1__i16_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x6ec9e41b, .data2 = 0x6709, .data3 = 0x5647, .data4 = .{ 0x99, 0x18, 0xa1, 0x27, 0x01, 0x10, 0xfc, 0x4e } };
};
pub const IReference__G1__u16_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Value: *const fn (this: *const IReference__G1__u16, result: *u16) callconv(.winapi) HRESULT,
};
pub const IReference__G1__u16 = extern struct {
    vtable: *const IReference__G1__u16_Vtbl,
    pub const Vtbl = IReference__G1__u16_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x5ab7d2c3, .data2 = 0x6b62, .data3 = 0x5e71, .data4 = .{ 0xa4, 0xb6, 0x2d, 0x49, 0xc4, 0xf2, 0x38, 0xfd } };
};
pub const IReference__G1__i32_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Value: *const fn (this: *const IReference__G1__i32, result: *i32) callconv(.winapi) HRESULT,
};
pub const IReference__G1__i32 = extern struct {
    vtable: *const IReference__G1__i32_Vtbl,
    pub const Vtbl = IReference__G1__i32_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x548cefbd, .data2 = 0xbc8a, .data3 = 0x5fa0, .data4 = .{ 0x8d, 0xf2, 0x95, 0x74, 0x40, 0xfc, 0x8b, 0xf4 } };
};
pub const IReference__G1__u32_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Value: *const fn (this: *const IReference__G1__u32, result: *u32) callconv(.winapi) HRESULT,
};
pub const IReference__G1__u32 = extern struct {
    vtable: *const IReference__G1__u32_Vtbl,
    pub const Vtbl = IReference__G1__u32_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x513ef3af, .data2 = 0xe784, .data3 = 0x5325, .data4 = .{ 0xa9, 0x1e, 0x97, 0xc2, 0xb8, 0x11, 0x1c, 0xf3 } };
};
pub const IReference__G1__i64_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Value: *const fn (this: *const IReference__G1__i64, result: *i64) callconv(.winapi) HRESULT,
};
pub const IReference__G1__i64 = extern struct {
    vtable: *const IReference__G1__i64_Vtbl,
    pub const Vtbl = IReference__G1__i64_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x4dda9e24, .data2 = 0xe69f, .data3 = 0x5c6a, .data4 = .{ 0xa0, 0xa6, 0x93, 0x42, 0x73, 0x65, 0xaf, 0x2a } };
};
pub const IReference__G1__u64_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Value: *const fn (this: *const IReference__G1__u64, result: *u64) callconv(.winapi) HRESULT,
};
pub const IReference__G1__u64 = extern struct {
    vtable: *const IReference__G1__u64_Vtbl,
    pub const Vtbl = IReference__G1__u64_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x6755e376, .data2 = 0x53bb, .data3 = 0x568b, .data4 = .{ 0xa1, 0x1d, 0x17, 0x23, 0x98, 0x68, 0x30, 0x9e } };
};
pub const IReference__G1__f32_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Value: *const fn (this: *const IReference__G1__f32, result: *f32) callconv(.winapi) HRESULT,
};
pub const IReference__G1__f32 = extern struct {
    vtable: *const IReference__G1__f32_Vtbl,
    pub const Vtbl = IReference__G1__f32_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x719cc2ba, .data2 = 0x3e76, .data3 = 0x5def, .data4 = .{ 0x9f, 0x1a, 0x38, 0xd8, 0x5a, 0x14, 0x5e, 0xa8 } };
};
pub const IReference__G1__f64_Vtbl = extern struct {
    base: IInspectable_Vtbl,
    get_Value: *const fn (this: *const IReference__G1__f64, result: *f64) callconv(.winapi) HRESULT,
};
pub const IReference__G1__f64 = extern struct {
    vtable: *const IReference__G1__f64_Vtbl,
    pub const Vtbl = IReference__G1__f64_Vtbl;
    pub const IID: GUID = .{ .data1 = 0x2f2d6c29, .data2 = 0x5473, .data3 = 0x5f3e, .data4 = .{ 0x92, 0xe7, 0x96, 0x57, 0x2b, 0xb9, 0x90, 0xe2 } };
};
