//! `winbindgen` — `.winmd` → `.zig` code generator and comptime projector.
//!
//! Phase 3 target: a CLI compatible with `windows-bindgen` that reads
//! the filter manifests under `tools/bindings/src/*.txt` and emits
//! namespaced `.zig` files into `packages/win-sys/src/` and
//! `packages/win/src/`.
//!
//! Phase 4 target: `project(.{ .filter = ... })` — a `comptime` function
//! that materializes the requested subset of the API directly using
//! `@Struct`, `@Enum`, and `@Union` (the per-kind type-creating builtins
//! introduced in Zig 0.16). No generated source files.

const std = @import("std");
const winmd = @import("winmd");

/// `TypeAttributes.Interface` (ECMA-335 §II.23.1.15) — set on every
/// TypeDef representing a COM / WinRT interface.
const TYPE_ATTR_INTERFACE: u32 = 0x20;

/// Ordered set of Windows.* namespaces referenced by the types
/// written during a single `emitNamespace` call. `emitNamespace`
/// drains the set after the body is produced and emits a sorted
/// `const @"<ns>" = @import("<ns>.zig");` alias for each entry, so
/// the cross-namespace qualifiers `writeZigTy` emits resolve against
/// something concrete.
///
/// Keys point into the mmapped `#Strings` blob, so their lifetime
/// matches the `winmd.File`'s — no copying needed.
const CrossNsSet = std.StringArrayHashMapUnmanaged(void);

/// Is `ns` a namespace we are willing to emit a cross-namespace
/// import alias for?  Today only `Windows.*` (and the bare root
/// `Windows`) qualify — `System.Guid`, `System.Object`, etc. are
/// either aliased to primitives by the emitter or fall through to
/// the opaque fallback, so qualifying them as `@"System".Guid` and
/// generating a dangling `@import("System.zig")` would just noise up
/// the output.
fn isProjectableNs(ns: []const u8) bool {
    return std.mem.eql(u8, ns, "Windows") or std.mem.startsWith(u8, ns, "Windows.");
}

/// Placeholder — full CLI lands later in Phase 3.
pub fn generate(_: std.mem.Allocator) !void {}

/// Emit every supported declaration for `namespace` to `writer`,
/// preceded by a header that imports the win-core primitives
/// (`HRESULT`, `HSTRING`, `IInspectable_Vtbl`, ...) the generated
/// code depends on. The output is a self-contained Zig source file
/// modulo cross-namespace type references.
///
/// Order:
///   1. IID GUID constants (`emitIidConstants`)
///   2. Enum declarations (`emitEnums`)
///   3. Value-type structs (`emitStructs`)
///   4. Interface handle structs (`emitInterfaceHandles`)
///   5. Runtime-class handle structs (`emitRuntimeClasses`)
///   6. Interface vtable structs (`emitInterfaceVtbls`)
///
/// Handles are declared before vtbls so the typed `class_name` and
/// default-interface pointers inside each vtbl resolve against an
/// already-declared struct.
pub fn emitNamespace(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
) !void {
    // Buffer the body into an arena-backed `Allocating` writer so the
    // cross-namespace alias list at the top is emitted *after* all
    // sub-emitters have had a chance to report their references via
    // the shared `cross` set. The arena already bounds the lifetime
    // of everything in this call, so no explicit `deinit`.
    var cross: CrossNsSet = .empty;
    var body: std.Io.Writer.Allocating = .init(arena);
    const body_writer = &body.writer;

    try emitIidConstants(body_writer, arena, file, namespace);
    try emitEnums(body_writer, arena, file, namespace);
    try emitStructsImpl(body_writer, arena, file, namespace, &cross);
    try emitInterfaceHandles(body_writer, arena, file, namespace, &cross);
    try emitDelegates(body_writer, file, namespace);
    try emitRuntimeClasses(body_writer, arena, file, namespace, &cross);
    try emitInterfaceVtblsImpl(body_writer, arena, file, namespace, &cross);
    try emitFreeFunctions(body_writer, arena, file, namespace, &cross);
    try emitConstants(body_writer, arena, file, namespace);

    try writer.writeAll(
        \\// Generated by winbindgen — do not edit.
        \\const win_core = @import("win-core");
        \\const HRESULT = win_core.HRESULT;
        \\const HSTRING = win_core.HSTRING;
        \\const GUID = win_core.GUID;
        \\const BOOL = win_core.BOOL;
        \\const IInspectable_Vtbl = win_core.IInspectable_Vtbl;
        \\
    );

    // Stable alphabetical order keeps the output diffable.
    const keys = cross.keys();
    const sorted = try arena.dupe([]const u8, keys);
    std.mem.sort([]const u8, sorted, {}, struct {
        fn lt(_: void, a: []const u8, b: []const u8) bool {
            return std.mem.lessThan(u8, a, b);
        }
    }.lt);
    for (sorted) |ns| {
        try writer.print("const @\"{s}\" = @import(\"{s}.zig\");\n", .{ ns, ns });
    }
    try writer.writeAll("\n");

    try writer.writeAll(body.written());
}

/// Write every `IID_<Name>` constant for interfaces in `namespace` to
/// `writer`, in TypeDef row order. Skips types that lack a
/// `GuidAttribute` (e.g. dispinterface forwards without a runtime IID).
///
/// `arena` is used for attribute-arg decoding; the caller owns its
/// lifetime. Typical use is to pass a `std.heap.ArenaAllocator`
/// allocator and reset it after each namespace.
pub fn emitIidConstants(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
) !void {
    const rows = file.rowCount(.type_def);
    var row: u32 = 0;
    while (row < rows) : (row += 1) {
        const ns = file.str(.type_def, row, 2);
        if (!std.mem.eql(u8, ns, namespace)) continue;

        const flags = file.cell(.type_def, row, 0);
        if ((flags & TYPE_ATTR_INTERFACE) == 0) continue;

        const attr_row = winmd.findAttribute(file, .type_def, row, "GuidAttribute") orelse continue;
        const args = winmd.readAttributeArgs(arena, file, attr_row) catch continue;
        if (args.len < 11) continue;

        var parts: [11]u64 = undefined;
        inline for (0..11) |i| {
            parts[i] = switch (args[i].value) {
                .u32_val => |v| v,
                .u16_val => |v| v,
                .u8_val => |v| v,
                else => return error.BadGuidAttribute,
            };
        }

        const name = file.str(.type_def, row, 1);
        // Skip WinRT parameterized-generic typedefs (names like
        // `IAsyncOperation\`1`). `\`` is not a legal Zig identifier
        // character and instantiating generics is deferred to v0.2.
        if (std.mem.indexOfScalar(u8, name, '`') != null) continue;
        try writer.print(
            \\pub const IID_{s}: GUID = .{{
            \\    .data1 = 0x{X:0>8},
            \\    .data2 = 0x{X:0>4},
            \\    .data3 = 0x{X:0>4},
            \\    .data4 = .{{ 0x{X:0>2}, 0x{X:0>2}, 0x{X:0>2}, 0x{X:0>2}, 0x{X:0>2}, 0x{X:0>2}, 0x{X:0>2}, 0x{X:0>2} }},
            \\}};
            \\
        ,
            .{
                name,
                parts[0],
                parts[1],
                parts[2],
                parts[3],
                parts[4],
                parts[5],
                parts[6],
                parts[7],
                parts[8],
                parts[9],
                parts[10],
            },
        );
    }
}

test "placeholder" {
    _ = winmd;
    try std.testing.expect(true);
}

/// Emit `pub extern "<dll>" fn Name(...) callconv(.winapi) Ret;`
/// declarations for every P/Invoke method inside the magic `Apis`
/// TypeDef of a Win32 namespace.
///
/// `Apis` is how MIDL surfaces free functions in .winmd: the module
/// holds one `Apis` class per namespace whose (static) methods are
/// the DLL exports. Each method row has a matching `ImplMap` row
/// pointing at a `ModuleRef` that names the owning DLL and the
/// (possibly renamed) import.
///
/// Methods whose signature contains a type the first-slice type
/// mapper can't render are silently skipped, matching the existing
/// struct / interface-handle fallback behavior. Methods whose
/// imported name differs from the MethodDef name (ordinal imports,
/// W/A suffixes added by the linker, etc.) are skipped for now —
/// they'll land once `@extern(.{ .name = ... })` support is wired
/// through the emitter.
pub fn emitFreeFunctions(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
    cross: *CrossNsSet,
) !void {
    const rows = file.rowCount(.type_def);
    var row: u32 = 0;
    while (row < rows) : (row += 1) {
        if (!std.mem.eql(u8, file.str(.type_def, row, 2), namespace)) continue;
        if (!std.mem.eql(u8, file.str(.type_def, row, 1), "Apis")) continue;

        const methods = file.list(.type_def, row, 5, .method_def);
        var m: u32 = methods.start;
        while (m < methods.end) : (m += 1) {
            const impl_map_row = file.findImplMap(m) orelse continue;

            const method_name = file.str(.method_def, m, 3);
            const import_name = file.implMapImportName(impl_map_row);

            const sig_blob = file.blob(.method_def, m, 4);
            const sig = winmd.readMethodSignature(arena, file, sig_blob) catch continue;
            if (!canRepresent(sig.return_type)) continue;
            var all_ok = true;
            for (sig.params) |p| {
                if (!canRepresent(p)) {
                    all_ok = false;
                    break;
                }
            }
            if (!all_ok) continue;

            const dll_full = file.implMapDll(impl_map_row);
            const dll_base = stripDllSuffix(dll_full);

            if (std.mem.eql(u8, method_name, import_name)) {
                try writer.print("pub extern \"{s}\" fn {s}", .{ dll_base, method_name });
                try writeFnSig(writer, arena, sig, namespace, cross, true);
                try writer.writeAll(";\n");
            } else {
                // Renamed / ordinal-only import: metadata's
                // MethodDef.Name is the Zig-facing identifier,
                // while ImplMap.ImportName is the real symbol or
                // "#<ordinal>". Use `@extern` so the two can differ.
                try writer.print("pub const {s}: *const fn ", .{method_name});
                try writeFnSig(writer, arena, sig, namespace, cross, false);
                try writer.writeAll(" = @extern(*const fn ");
                try writeFnSig(writer, arena, sig, namespace, cross, false);
                try writer.print(", .{{ .name = \"{s}\", .library_name = \"{s}\" }});\n", .{ import_name, dll_base });
            }
        }
    }
}

/// Write `(p0: T0, p1: T1, ...) callconv(.winapi) R` for a method
/// signature. When `with_names` is false, parameter names are omitted
/// so the text can stand in as a function *type* (used by `@extern`).
fn writeFnSig(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    sig: winmd.MethodSignature,
    namespace: []const u8,
    cross: *CrossNsSet,
    with_names: bool,
) !void {
    try writer.writeAll("(");
    for (sig.params, 0..) |p, i| {
        if (i != 0) try writer.writeAll(", ");
        if (with_names) try writer.print("p{d}: ", .{i});
        try writeParam(writer, arena, p, namespace, cross);
    }
    try writer.writeAll(") callconv(.winapi) ");
    if (sig.return_type == .void) {
        try writer.writeAll("void");
    } else {
        _ = try writeZigTy(writer, arena, sig.return_type, namespace, cross);
    }
}

/// Strip a trailing ".dll" (case-insensitive) from `name`. Zig's
/// `extern "<lib>"` string is matched against the import library's
/// basename without extension, so "KERNEL32.dll" must surface as
/// "KERNEL32".
fn stripDllSuffix(name: []const u8) []const u8 {
    if (name.len < 4) return name;
    const tail = name[name.len - 4 ..];
    if (std.ascii.eqlIgnoreCase(tail, ".dll")) return name[0 .. name.len - 4];
    return name;
}

/// Return true if `(namespace, name)` is already surfaced by the
/// `emitNamespace` prelude as an alias into `win-core`. Such types
/// must not be re-emitted from metadata or Zig would see two
/// top-level decls with the same name.
fn isPreludeAlias(namespace: []const u8, name: []const u8) bool {
    if (std.mem.eql(u8, namespace, "Windows.Win32.Foundation")) {
        if (std.mem.eql(u8, name, "HRESULT")) return true;
        if (std.mem.eql(u8, name, "BOOL")) return true;
    }
    if (std.mem.eql(u8, namespace, "Windows.Win32.System.WinRT")) {
        if (std.mem.eql(u8, name, "HSTRING")) return true;
    }
    return false;
}

/// Emit `pub const NAME: T = VAL;` declarations for every Win32
/// primitive-integer constant in `namespace`. Constants live as
/// static+literal fields of the magic `Apis` TypeDef, with their
/// value in the `Constant` metadata table.
///
/// Only primitive integer / bool / char fields are emitted. Fields
/// whose type is a named typedef (HANDLE, HRESULT, NTSTATUS, GUID…),
/// a string, or a float are skipped — they'll come once the relevant
/// type alias / literal encoders exist.
pub fn emitConstants(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
) !void {
    // FieldAttributes — ECMA-335 §II.23.1.5.
    const FIELD_ATTR_STATIC: u32 = 0x10;
    const FIELD_ATTR_LITERAL: u32 = 0x40;

    const rows = file.rowCount(.type_def);
    var row: u32 = 0;
    while (row < rows) : (row += 1) {
        if (!std.mem.eql(u8, file.str(.type_def, row, 2), namespace)) continue;
        if (!std.mem.eql(u8, file.str(.type_def, row, 1), "Apis")) continue;

        const fields = file.list(.type_def, row, 4, .field);
        var f: u32 = fields.start;
        while (f < fields.end) : (f += 1) {
            const attr = file.cell(.field, f, 0);
            if ((attr & FIELD_ATTR_STATIC) == 0) continue;
            if ((attr & FIELD_ATTR_LITERAL) == 0) continue;

            const ty = winmd.readFieldSignature(arena, file, file.blob(.field, f, 2)) catch continue;
            const repr = zigReprFor(ty) orelse continue;

            // HasConstant coded index: tag 0 = Field, row is 1-based.
            const parent_tok = (@as(u32, f + 1) << 2) | 0;
            const range = file.equalRange(.constant, 1, parent_tok);
            if (range.start == range.end) continue;

            const type_code: u8 = @intCast(file.cell(.constant, range.start, 0) & 0xFF);
            const value_blob = file.blob(.constant, range.start, 2);
            const raw = readConstantValue(type_code, value_blob) orelse continue;

            const name = file.str(.field, f, 1);
            if (isSignedRepr(ty)) {
                // Sign-extend from the original width so the printed
                // decimal matches the intent of the metadata value
                // (e.g. `-1` not `0xFFFFFFFF`).
                const signed: i64 = switch (ty) {
                    .i8 => @as(i64, @as(i8, @bitCast(@as(u8, @truncate(raw))))),
                    .i16 => @as(i64, @as(i16, @bitCast(@as(u16, @truncate(raw))))),
                    .i32 => @as(i64, @as(i32, @bitCast(@as(u32, @truncate(raw))))),
                    .i64 => @bitCast(raw),
                    else => @bitCast(raw),
                };
                try writer.print("pub const {s}: {s} = {d};\n", .{ name, repr, signed });
            } else {
                try writer.print("pub const {s}: {s} = {d};\n", .{ name, repr, raw });
            }
        }
    }
}

/// Emit a `pub const <Name> = enum(<repr>) { ... };` for every enum
/// TypeDef in `namespace`. An enum is a TypeDef whose `Extends` column
/// resolves to `System.Enum`; its first field (instance, name `value__`)
/// carries the underlying integer type, and every subsequent field is a
/// `static literal` whose value lives in the Constant table.
///
/// Emitted enums are non-exhaustive (`_`) so that OR'd flag values —
/// common in `FlagsAttribute`-decorated enums — remain representable at
/// the API surface. Duplicate declared values would still be rejected by
/// the Zig compiler; if any such enum surfaces in metadata we'll need a
/// second strategy for that kind.
pub fn emitEnums(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
) !void {
    const rows = file.rowCount(.type_def);
    var row: u32 = 0;
    while (row < rows) : (row += 1) {
        if (!std.mem.eql(u8, file.str(.type_def, row, 2), namespace)) continue;

        const extends_tok = file.cell(.type_def, row, 3);
        if (extends_tok == 0) continue;
        const base = winmd.resolveTypeDefOrRefName(file, extends_tok) catch continue;
        if (!std.mem.eql(u8, base.namespace, "System") or !std.mem.eql(u8, base.name, "Enum")) continue;

        const fields = file.list(.type_def, row, 4, .field);
        if (fields.start == fields.end) continue;

        // Locate `value__` (instance field, FieldAttributes.SpecialName=0x200,
        // FieldAttributes.RTSpecialName=0x400). In practice it's always the
        // first field of the enum TypeDef; fall back to a name check.
        var repr_field: u32 = fields.start;
        const first_name = file.str(.field, fields.start, 1);
        if (!std.mem.eql(u8, first_name, "value__")) {
            var f: u32 = fields.start;
            while (f < fields.end) : (f += 1) {
                if (std.mem.eql(u8, file.str(.field, f, 1), "value__")) {
                    repr_field = f;
                    break;
                }
            } else continue;
        }

        const repr_ty = winmd.readFieldSignature(arena, file, file.blob(.field, repr_field, 2)) catch continue;
        const repr_str = zigReprFor(repr_ty) orelse continue;

        const name = file.str(.type_def, row, 1);
        if (std.mem.indexOfScalar(u8, name, '`') != null) continue;
        try writer.print("pub const {s} = enum({s}) {{\n", .{ name, repr_str });

        var f: u32 = fields.start;
        while (f < fields.end) : (f += 1) {
            if (f == repr_field) continue;

            // Static literal fields are flagged FieldAttributes.Static=0x10 |
            // Literal=0x40. The Constant row is sorted by Parent so a
            // binary-search range of one row is expected.
            const parent_tok = (@as(u32, f + 1) << 2) | 0; // HasConstant tag 0 = Field
            const range = file.equalRange(.constant, 1, parent_tok);
            if (range.start == range.end) continue;

            const type_code: u8 = @intCast(file.cell(.constant, range.start, 0) & 0xFF);
            const value_blob = file.blob(.constant, range.start, 2);
            const raw = readConstantValue(type_code, value_blob) orelse continue;

            const variant_name = file.str(.field, f, 1);
            // Print as signed when underlying type is signed, unsigned
            // otherwise; match the declared enum tag type.
            if (isSignedRepr(repr_ty)) {
                const signed: i64 = @bitCast(raw);
                try writer.print("    {s} = {d},\n", .{ variant_name, signed });
            } else {
                try writer.print("    {s} = {d},\n", .{ variant_name, raw });
            }
        }

        try writer.writeAll("    _,\n};\n");
    }
}

/// Map a primitive `Ty` to its Zig name for use as an enum tag type.
/// Returns null for anything that can't back a CLI enum.
fn zigReprFor(ty: winmd.Ty) ?[]const u8 {
    return switch (ty) {
        .i8 => "i8",
        .u8 => "u8",
        .i16 => "i16",
        .u16 => "u16",
        .i32 => "i32",
        .u32 => "u32",
        .i64 => "i64",
        .u64 => "u64",
        else => null,
    };
}

fn isSignedRepr(ty: winmd.Ty) bool {
    return switch (ty) {
        .i8, .i16, .i32, .i64 => true,
        else => false,
    };
}

/// Decode a Constant.Value blob as a `u64` bit pattern. Only integer
/// ELEMENT_TYPE codes relevant to enums are handled. Returns null for
/// unsupported or truncated blobs.
fn readConstantValue(type_code: u8, blob: []const u8) ?u64 {
    // ELEMENT_TYPE codes from ECMA-335 §II.23.1.16.
    const ET_BOOLEAN: u8 = 0x02;
    const ET_CHAR: u8 = 0x03;
    const ET_I1: u8 = 0x04;
    const ET_U1: u8 = 0x05;
    const ET_I2: u8 = 0x06;
    const ET_U2: u8 = 0x07;
    const ET_I4: u8 = 0x08;
    const ET_U4: u8 = 0x09;
    const ET_I8: u8 = 0x0A;
    const ET_U8: u8 = 0x0B;
    switch (type_code) {
        ET_BOOLEAN, ET_I1, ET_U1 => {
            if (blob.len < 1) return null;
            return @as(u64, blob[0]);
        },
        ET_CHAR, ET_I2, ET_U2 => {
            if (blob.len < 2) return null;
            return @as(u64, std.mem.readInt(u16, blob[0..2], .little));
        },
        ET_I4, ET_U4 => {
            if (blob.len < 4) return null;
            return @as(u64, std.mem.readInt(u32, blob[0..4], .little));
        },
        ET_I8, ET_U8 => {
            if (blob.len < 8) return null;
            return std.mem.readInt(u64, blob[0..8], .little);
        },
        else => return null,
    }
}

test "emitIidConstants writes IStringable from Windows.Foundation" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);
    _ = &file;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    try emitIidConstants(&buf.writer, arena.allocator(), &file, "Windows.Foundation");
    const out = buf.written();

    // IStringable's IID is the canonical `{96369F54-8EB6-48F0-ABCE-C1B211E627C3}`.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const IID_IStringable: GUID") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".data1 = 0x96369F54") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".data2 = 0x8EB6") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".data3 = 0x48F0") != null);
    // data4 bytes: AB CE C1 B2 11 E6 27 C3
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "0xAB, 0xCE, 0xC1, 0xB2, 0x11, 0xE6, 0x27, 0xC3",
    ) != null);

    // Make sure we emit more than one entry — count IID_ prefixes.
    var count: usize = 0;
    var search = out;
    while (std.mem.indexOf(u8, search, "pub const IID_")) |idx| {
        count += 1;
        search = search[idx + 1 ..];
    }
    try std.testing.expect(count > 10);
}

/// Emit a `<Name>_Vtbl extern struct` per interface in `namespace`.
///
/// First-slice emission: each method is typed as `*const anyopaque`
/// so we prove the method walker independently of the full
/// type-mapping layer. Vtbl field order matches MethodDef row order,
/// which is the ABI slot order for COM / WinRT. A later slice will
/// replace the opaque fields with real
/// `*const fn(...) callconv(.winapi) HRESULT` function pointers
/// derived from the MethodDef signature blob.
///
/// Every WinRT interface's first three slots are IUnknown methods
/// followed by three IInspectable methods — captured here by
/// `base: IInspectable_Vtbl`. Classic COM interfaces that extend
/// IUnknown directly are out of scope for this slice (the WinRT
/// metadata we consume has none).
pub fn emitInterfaceVtbls(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
) !void {
    var cross: CrossNsSet = .empty;
    try emitInterfaceVtblsImpl(writer, arena, file, namespace, &cross);
}

fn emitInterfaceVtblsImpl(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
    cross: *CrossNsSet,
) !void {
    const rows = file.rowCount(.type_def);
    var row: u32 = 0;
    while (row < rows) : (row += 1) {
        if (!std.mem.eql(u8, file.str(.type_def, row, 2), namespace)) continue;
        const flags = file.cell(.type_def, row, 0);
        if ((flags & TYPE_ATTR_INTERFACE) == 0) continue;

        const name = file.str(.type_def, row, 1);
        // Skip generic placeholders like `IVector`1` — a later slice
        // handles parameterised vtbls.
        if (std.mem.indexOfScalar(u8, name, '`') != null) continue;

        try writer.print(
            \\pub const {s}_Vtbl = extern struct {{
            \\    base: IInspectable_Vtbl,
            \\
        , .{name});

        const methods = file.list(.type_def, row, 5, .method_def);
        var m = methods.start;
        while (m < methods.end) : (m += 1) {
            const method_name = file.str(.method_def, m, 3);
            try writer.print("    {s}: ", .{method_name});
            try writeMethodPointer(writer, arena, file, m, name, namespace, cross);
            try writer.writeAll(",\n");
        }

        try writer.writeAll("};\n");
    }
}

/// Emit a top-level handle type for each non-generic interface in
/// `namespace`. Shape:
///
///     pub const IStringable = extern struct {
///         vtable: *const IStringable_Vtbl,
///     };
///
/// This is the canonical COM object shape: every interface pointer
/// points to an object whose first word is the vtbl pointer. Having a
/// named type per interface lets callers write `*IStringable` rather
/// than juggling raw `*anyopaque` values, and is the foundation for a
/// later slice that replaces `class_name → *anyopaque` in vtbl params
/// with typed pointers.
///
/// Must be paired with `emitInterfaceVtbls` in the same compilation
/// unit (or with the vtbls in scope via import), since the handle
/// references `<Name>_Vtbl` directly.
pub fn emitInterfaceHandles(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
    cross: *CrossNsSet,
) !void {
    const rows = file.rowCount(.type_def);
    var row: u32 = 0;
    while (row < rows) : (row += 1) {
        if (!std.mem.eql(u8, file.str(.type_def, row, 2), namespace)) continue;
        const flags = file.cell(.type_def, row, 0);
        if ((flags & TYPE_ATTR_INTERFACE) == 0) continue;

        const name = file.str(.type_def, row, 1);
        if (std.mem.indexOfScalar(u8, name, '`') != null) continue;

        try writer.print(
            \\pub const {s} = extern struct {{
            \\    vtable: *const {s}_Vtbl,
            \\
        , .{ name, name });

        try writeInterfaceIid(writer, arena, file, row);
        try writeIUnknownWrappers(writer, name);

        const methods = file.list(.type_def, row, 5, .method_def);
        var m = methods.start;
        while (m < methods.end) : (m += 1) {
            try writeMethodWrapper(writer, arena, file, m, name, namespace, cross);
        }

        try writer.writeAll("};\n");
    }
}

/// Emit `pub const IID: GUID = .{ ... };` inside an interface handle's
/// struct body when the TypeDef carries a `GuidAttribute`. The WinRT
/// `Windows.Foundation.Metadata.GuidAttribute` ctor has eleven
/// positional args (`u32, u16, u16, u8, u8, u8, u8, u8, u8, u8, u8`)
/// that assemble into a standard COM GUID. Interfaces with no Guid
/// (generic parameterizations, odd synthetic types) just get no IID
/// decl — callers that need it will have to fall back to hand-written
/// constants until a later slice handles them.
fn writeInterfaceIid(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    type_def_row: u32,
) !void {
    const attr_row = winmd.findAttribute(file, .type_def, type_def_row, "GuidAttribute") orelse return;

    const args = winmd.readAttributeArgs(arena, file, attr_row) catch return;
    if (args.len != 11) return;

    const d1 = switch (args[0].value) {
        .u32_val => |v| v,
        else => return,
    };
    const d2 = switch (args[1].value) {
        .u16_val => |v| v,
        else => return,
    };
    const d3 = switch (args[2].value) {
        .u16_val => |v| v,
        else => return,
    };
    var d4: [8]u8 = undefined;
    for (0..8) |i| {
        d4[i] = switch (args[3 + i].value) {
            .u8_val => |v| v,
            else => return,
        };
    }

    try writer.print(
        "    pub const IID: GUID = .{{ .data1 = 0x{x:0>8}, .data2 = 0x{x:0>4}, .data3 = 0x{x:0>4}, .data4 = .{{ 0x{x:0>2}, 0x{x:0>2}, 0x{x:0>2}, 0x{x:0>2}, 0x{x:0>2}, 0x{x:0>2}, 0x{x:0>2}, 0x{x:0>2} }} }};\n",
        .{ d1, d2, d3, d4[0], d4[1], d4[2], d4[3], d4[4], d4[5], d4[6], d4[7] },
    );
}

/// Emit typed `QueryInterface` / `AddRef` / `Release` method
/// wrappers plus a `cast(comptime T)` convenience on a WinRT
/// interface handle. Every WinRT vtbl's first three slots are the
/// IUnknown methods (reached here as `self.vtable.base.base.*` —
/// `base: IInspectable_Vtbl` which has its own `base: IUnknown_Vtbl`).
/// The underlying fn pointers take `this: *anyopaque`, so we
/// `@ptrCast` the typed `self` at each call site and keep the
/// caller's API pointer-typed. `cast` looks up `T.IID` (emitted on
/// every interface by `writeInterfaceIid`) and returns a typed
/// `?*const T` without the caller ever seeing `*anyopaque`.
fn writeIUnknownWrappers(writer: *std.Io.Writer, name: []const u8) !void {
    try writer.print(
        \\    pub fn QueryInterface(self: *const {s}, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {{
        \\        return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);
        \\    }}
        \\    pub fn AddRef(self: *const {s}) callconv(.winapi) u32 {{
        \\        return self.vtable.base.base.AddRef(@ptrCast(@constCast(self)));
        \\    }}
        \\    pub fn Release(self: *const {s}) callconv(.winapi) u32 {{
        \\        return self.vtable.base.base.Release(@ptrCast(@constCast(self)));
        \\    }}
        \\    pub fn cast(self: *const {s}, comptime T: type) ?*const T {{
        \\        var out: ?*anyopaque = null;
        \\        if (self.QueryInterface(&T.IID, &out) < 0) return null;
        \\        return @ptrCast(@alignCast(out));
        \\    }}
        \\
    , .{ name, name, name, name });
}

/// Emit a method wrapper (`pub fn Name(self, args) HRESULT { return self.vtable.Name(self, args); }`)
/// for one MethodDef row — but only if the signature is fully
/// representable. Unrepresentable methods are skipped entirely (the
/// raw vtbl slot still falls back to `*const anyopaque`, so callers
/// can still reach them by hand).
fn writeMethodWrapper(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    method_row: u32,
    this_name: []const u8,
    current_namespace: []const u8,
    cross: *CrossNsSet,
) !void {
    const method_name = file.str(.method_def, method_row, 3);
    const sig_blob = file.blob(.method_def, method_row, 4);
    const sig = winmd.readMethodSignature(arena, file, sig_blob) catch return;

    if (!canRepresent(sig.return_type)) return;
    for (sig.params) |p| {
        if (!canRepresent(p)) return;
    }

    try writer.print("    pub fn {s}(self: *const {s}", .{ method_name, this_name });
    for (sig.params, 0..) |p, i| {
        try writer.print(", p{d}: ", .{i});
        try writeParam(writer, arena, p, current_namespace, cross);
    }
    if (sig.return_type != .void) {
        try writer.writeAll(", result: *");
        _ = try writeZigTy(writer, arena, sig.return_type, current_namespace, cross);
    }
    try writer.print(") callconv(.winapi) HRESULT {{\n        return self.vtable.{s}(self", .{method_name});
    for (sig.params, 0..) |_, i| {
        try writer.print(", p{d}", .{i});
    }
    if (sig.return_type != .void) {
        try writer.writeAll(", result");
    }
    try writer.writeAll(");\n    }\n");
}

/// Emit a function-pointer type for a single MethodDef row, WinRT-ABI
/// shaped: `*const fn(this: *const IFace, <in/out params>) callconv(.winapi) HRESULT`.
///
/// `this_name` is the simple name of the enclosing interface; it
/// produces a typed self-pointer so method wrappers on the handle
/// struct can pass `self` through without casts.
///
/// Any type in the signature that the first-slice type mapper cannot
/// render falls the whole method back to `*const anyopaque`, so new
/// type support can be added incrementally without breaking existing
/// fixtures.
fn writeMethodPointer(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    method_row: u32,
    this_name: []const u8,
    current_namespace: []const u8,
    cross: *CrossNsSet,
) !void {
    const sig_blob = file.blob(.method_def, method_row, 4);
    const sig = winmd.readMethodSignature(arena, file, sig_blob) catch {
        try writer.writeAll("*const anyopaque");
        return;
    };

    // Representability check: every param + return must be renderable
    // by `writeZigTy`, otherwise emit the opaque fallback.
    if (!canRepresent(sig.return_type)) {
        try writer.writeAll("*const anyopaque");
        return;
    }
    for (sig.params) |p| {
        if (!canRepresent(p)) {
            try writer.writeAll("*const anyopaque");
            return;
        }
    }

    try writer.print("*const fn (this: *const {s}", .{this_name});
    for (sig.params, 0..) |p, i| {
        try writer.print(", p{d}: ", .{i});
        try writeParam(writer, arena, p, current_namespace, cross);
    }
    if (sig.return_type != .void) {
        try writer.writeAll(", result: *");
        _ = try writeZigTy(writer, arena, sig.return_type, current_namespace, cross);
    }
    try writer.writeAll(") callconv(.winapi) HRESULT");
}

/// One parameter slot. WinRT conventions: `[out]` params arrive as
/// `ELEMENT_TYPE_BYREF T` in the metadata blob (decoded as `ref_mut`
/// / `ref_const` here). We render those as `*T` / `*const T`. In
/// params are passed by value.
fn writeParam(
    writer: *std.Io.Writer,
    gpa: std.mem.Allocator,
    ty: winmd.Ty,
    current_namespace: []const u8,
    cross: *CrossNsSet,
) !void {
    switch (ty) {
        .ref_mut => |inner| {
            try writer.writeAll("*");
            _ = try writeZigTy(writer, gpa, inner.*, current_namespace, cross);
        },
        .ref_const => |inner| {
            try writer.writeAll("*const ");
            _ = try writeZigTy(writer, gpa, inner.*, current_namespace, cross);
        },
        else => _ = try writeZigTy(writer, gpa, ty, current_namespace, cross),
    }
}

/// Returns true iff `writeZigTy` / `writeParam` can render `ty` as
/// a concrete Zig type with current first-slice support.
fn canRepresent(ty: winmd.Ty) bool {
    return switch (ty) {
        .void,
        .bool,
        .char,
        .i8,
        .u8,
        .i16,
        .u16,
        .i32,
        .u32,
        .i64,
        .u64,
        .f32,
        .f64,
        .string,
        .class_name,
        .value_name,
        => true,
        .ref_mut, .ref_const => |inner| canRepresent(inner.*),
        .ptr_mut => |p| canRepresent(p.inner.*),
        .ptr_const => |p| canRepresent(p.inner.*),
        else => false,
    };
}

/// Write a Zig type name for `ty`. Caller must have already verified
/// via `canRepresent` that `ty` is supported; this function never
/// returns `false` for supported input.
fn writeZigTy(
    writer: *std.Io.Writer,
    gpa: std.mem.Allocator,
    ty: winmd.Ty,
    current_namespace: []const u8,
    cross: *CrossNsSet,
) !bool {
    switch (ty) {
        .void => try writer.writeAll("void"),
        .bool => try writer.writeAll("BOOL"),
        .char => try writer.writeAll("u16"),
        .i8 => try writer.writeAll("i8"),
        .u8 => try writer.writeAll("u8"),
        .i16 => try writer.writeAll("i16"),
        .u16 => try writer.writeAll("u16"),
        .i32 => try writer.writeAll("i32"),
        .u32 => try writer.writeAll("u32"),
        .i64 => try writer.writeAll("i64"),
        .u64 => try writer.writeAll("u64"),
        .f32 => try writer.writeAll("f32"),
        .f64 => try writer.writeAll("f64"),
        .string => try writer.writeAll("HSTRING"),
        // WinRT / COM interface reference. In metadata this is
        // inherently a pointer — ELEMENT_TYPE_CLASS represents the
        // object by reference — so we emit `*<Name>` pointing at the
        // handle struct from `emitInterfaceHandles`. If `tn` lives in
        // a different `Windows.*` namespace we qualify the reference
        // as `*@"Windows.Foo".Name` and record `Windows.Foo` in
        // `cross` so `emitNamespace` adds the matching `@import`.
        .class_name => |tn| {
            // Generic WinRT interfaces (`IReference\`1` etc.) cannot
            // round-trip through a Zig identifier. Treat them as
            // opaque pointers until parameterized generics land in
            // a later phase.
            if (std.mem.indexOfScalar(u8, tn.name, '`') != null) {
                try writer.writeAll("*anyopaque");
            } else if (isProjectableNs(tn.namespace) and !std.mem.eql(u8, tn.namespace, current_namespace)) {
                try cross.put(gpa, tn.namespace, {});
                try writer.print("*@\"{s}\".{s}", .{ tn.namespace, tn.name });
            } else {
                try writer.print("*{s}", .{tn.name});
            }
        },
        // WinRT value type (enum or struct) passed by value. Same
        // cross-namespace rule as `class_name`, just without the
        // leading `*`.
        .value_name => |tn| {
            if (std.mem.indexOfScalar(u8, tn.name, '`') != null) {
                return false;
            } else if (std.mem.eql(u8, tn.namespace, "System") and std.mem.eql(u8, tn.name, "Guid")) {
                // `System.Guid` is the ECMA-335 name for the same
                // struct `win-core` projects as `GUID`.
                try writer.writeAll("GUID");
            } else if (isProjectableNs(tn.namespace) and !std.mem.eql(u8, tn.namespace, current_namespace)) {
                try cross.put(gpa, tn.namespace, {});
                try writer.print("@\"{s}\".{s}", .{ tn.namespace, tn.name });
            } else {
                try writer.writeAll(tn.name);
            }
        },
        .ptr_mut => |p| {
            var d: u32 = 0;
            while (d < p.depth) : (d += 1) try writer.writeAll("*");
            return writeZigTy(writer, gpa, p.inner.*, current_namespace, cross);
        },
        .ptr_const => |p| {
            var d: u32 = 0;
            while (d < p.depth) : (d += 1) try writer.writeAll("*const ");
            return writeZigTy(writer, gpa, p.inner.*, current_namespace, cross);
        },
        else => return false,
    }
    return true;
}

test "emitInterfaceVtbls writes IStringable_Vtbl with ToString slot" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    try emitInterfaceVtbls(&buf.writer, arena.allocator(), &file, "Windows.Foundation");
    const out = buf.written();

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const IStringable_Vtbl = extern struct {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "base: IInspectable_Vtbl") != null);
    // IStringable.ToString: `HSTRING ToString()` → typed signature with
    // a trailing *HSTRING out param and HRESULT return.
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "ToString: *const fn (this: *const IStringable, result: *HSTRING) callconv(.winapi) HRESULT",
    ) != null);

    // IClosable.Close: `void Close()` → no trailing out param.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const IClosable_Vtbl = extern struct {") != null);
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "Close: *const fn (this: *const IClosable) callconv(.winapi) HRESULT",
    ) != null);

    // IUriRuntimeClassFactory.CreateUri(HSTRING uri) returns a
    // runtime class (`Uri`) — a class_name reference. With typed
    // interface handles the out param becomes `**Uri`.
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "CreateUri: *const fn (this: *const IUriRuntimeClassFactory, p0: HSTRING, result: **Uri) callconv(.winapi) HRESULT",
    ) != null);

    // IAsyncInfo.get_Status returns the `AsyncStatus` enum — a
    // by-value value_name reference. The mapper should emit the
    // short name verbatim so downstream can resolve it via @import.
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "get_Status: *const fn (this: *const IAsyncInfo, result: *AsyncStatus) callconv(.winapi) HRESULT",
    ) != null);

    // At least one interface in Windows.Foundation uses types we don't
    // yet support (e.g. `IReference`1` methods with classes) — those
    // must degrade to opaque rather than fail the whole emit.
    try std.testing.expect(std.mem.indexOf(u8, out, "*const anyopaque") != null);
}

test "emitEnums writes AsyncStatus from Windows.Foundation" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    try emitEnums(&buf.writer, arena.allocator(), &file, "Windows.Foundation");
    const out = buf.written();

    // AsyncStatus is the canonical WinRT i32-backed async-operation enum.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const AsyncStatus = enum(i32) {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    Started = 0,") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    Completed = 1,") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    Canceled = 2,") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    Error = 3,") != null);
    // Non-exhaustive marker lets OR'd flag values in other enums remain
    // representable without re-declaration.
    try std.testing.expect(std.mem.indexOf(u8, out, "    _,\n};") != null);

    // At least one enum is expected in Windows.Foundation (AsyncStatus
    // above) — the exact count varies by metadata vintage.
    var count: usize = 0;
    var search = out;
    while (std.mem.indexOf(u8, search, "pub const ")) |idx| {
        count += 1;
        search = search[idx + 1 ..];
    }
    try std.testing.expect(count >= 1);
}

/// Emit `extern struct` declarations for every `System.ValueType`
/// TypeDef in `namespace` that isn't an enum and whose fields all
/// map to representable Zig types. Examples in Windows.Foundation:
/// `Point { X: f32, Y: f32 }`, `Rect { X, Y, Width, Height: f32 }`,
/// `TimeSpan { Duration: i64 }`.
///
/// First-slice scope:
/// * Only non-generic, non-nested value types.
/// * Only SequentialLayout (or AutoLayout, treated as sequential for
///   the handful of metadata quirks). ExplicitLayout / union-shaped
///   types are skipped — a later slice can emit `extern union`.
/// * If any instance field's type isn't currently representable
///   (e.g. a generic type arg), the whole struct is skipped rather
///   than emitted with a hole — this keeps the output compilable.
pub fn emitStructs(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
) !void {
    var cross: CrossNsSet = .empty;
    try emitStructsImpl(writer, arena, file, namespace, &cross);
}

fn emitStructsImpl(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
    cross: *CrossNsSet,
) !void {
    // TypeAttributes bits (ECMA-335 §II.23.1.15).
    const VISIBILITY_MASK: u32 = 0x7;
    const VIS_NOT_PUBLIC: u32 = 0x0;
    const VIS_PUBLIC: u32 = 0x1;
    const LAYOUT_MASK: u32 = 0x18;
    const LAYOUT_EXPLICIT: u32 = 0x10;
    // FieldAttributes.Static — enum literal fields and class-level
    // constants carry this bit and must be skipped when walking
    // struct instance fields.
    const FIELD_ATTR_STATIC: u32 = 0x10;

    const rows = file.rowCount(.type_def);
    var row: u32 = 0;
    while (row < rows) : (row += 1) {
        if (!std.mem.eql(u8, file.str(.type_def, row, 2), namespace)) continue;

        const flags = file.cell(.type_def, row, 0);
        const vis = flags & VISIBILITY_MASK;
        if (vis != VIS_NOT_PUBLIC and vis != VIS_PUBLIC) continue; // nested
        if ((flags & LAYOUT_MASK) == LAYOUT_EXPLICIT) continue;

        const extends_tok = file.cell(.type_def, row, 3);
        if (extends_tok == 0) continue;
        const base = winmd.resolveTypeDefOrRefName(file, extends_tok) catch continue;
        if (!std.mem.eql(u8, base.namespace, "System")) continue;
        if (!std.mem.eql(u8, base.name, "ValueType")) continue;

        const name = file.str(.type_def, row, 1);
        if (std.mem.indexOfScalar(u8, name, '`') != null) continue;
        if (isPreludeAlias(namespace, name)) continue;

        const field_list = file.list(.type_def, row, 4, .field);
        if (field_list.start == field_list.end) continue;

        // First pass: verify every non-static field is representable.
        // If anything is out of scope we skip the whole struct rather
        // than emit opaque fillers, which would break downstream
        // size/alignment assumptions at the ABI boundary.
        var all_ok = true;
        var f: u32 = field_list.start;
        while (f < field_list.end) : (f += 1) {
            const field_flags = file.cell(.field, f, 0);
            if ((field_flags & FIELD_ATTR_STATIC) != 0) continue;
            const ty = winmd.readFieldSignature(arena, file, file.blob(.field, f, 2)) catch {
                all_ok = false;
                break;
            };
            if (!canRepresent(ty)) {
                all_ok = false;
                break;
            }
        }
        if (!all_ok) continue;

        try writer.print("pub const {s} = extern struct {{\n", .{name});
        f = field_list.start;
        while (f < field_list.end) : (f += 1) {
            const field_flags = file.cell(.field, f, 0);
            if ((field_flags & FIELD_ATTR_STATIC) != 0) continue;
            const ty = winmd.readFieldSignature(arena, file, file.blob(.field, f, 2)) catch continue;
            const field_name = file.str(.field, f, 1);
            try writer.print("    {s}: ", .{field_name});
            _ = try writeZigTy(writer, arena, ty, namespace, cross);
            try writer.writeAll(",\n");
        }
        try writer.writeAll("};\n");
    }
}

test "emitStructs writes Point/Rect/TimeSpan from Windows.Foundation" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    try emitStructs(&buf.writer, arena.allocator(), &file, "Windows.Foundation");
    const out = buf.written();

    // Point — classic two-f32 struct, a canary for sequential layout.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Point = extern struct {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    X: f32,") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    Y: f32,") != null);

    // Rect — four f32s in declaration order.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Rect = extern struct {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    Width: f32,") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    Height: f32,") != null);

    // TimeSpan — single i64 field, exercises non-f32 primitives.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const TimeSpan = extern struct {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "    Duration: i64,") != null);
}

test "emitInterfaceHandles writes IStringable handle with method wrappers" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    var cross: CrossNsSet = .empty;

    try emitInterfaceHandles(&buf.writer, arena.allocator(), &file, "Windows.Foundation", &cross);
    const out = buf.written();

    // Canonical COM object layout: first word is the vtbl pointer,
    // followed by method wrappers that forward through the vtable.
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "pub const IStringable = extern struct {\n    vtable: *const IStringable_Vtbl,\n",
    ) != null);

    // The ToString wrapper forwards to `self.vtable.ToString(self, result)`.
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "pub fn ToString(self: *const IStringable, result: *HSTRING) callconv(.winapi) HRESULT {",
    ) != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "return self.vtable.ToString(self, result);") != null);

    // IUnknown wrappers reach the IUnknown slots at `vtable.base.base.*`
    // (IInspectable_Vtbl.base is IUnknown_Vtbl).
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "pub fn QueryInterface(self: *const IStringable, iid: *const GUID, interface: *?*anyopaque) callconv(.winapi) HRESULT {",
    ) != null);
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "return self.vtable.base.base.QueryInterface(@ptrCast(@constCast(self)), iid, interface);",
    ) != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub fn AddRef(self: *const IStringable) callconv(.winapi) u32 {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub fn Release(self: *const IStringable) callconv(.winapi) u32 {") != null);

    // `cast` is the typed QueryInterface convenience — looks up
    // `T.IID` (emitted by writeInterfaceIid on every interface).
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "pub fn cast(self: *const IStringable, comptime T: type) ?*const T {",
    ) != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "if (self.QueryInterface(&T.IID, &out) < 0) return null;") != null);

    // IStringable's IID from WinRT metadata: {96369f54-8eb6-48f0-abce-c1b211e627c3}.
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "pub const IID: GUID = .{ .data1 = 0x96369f54, .data2 = 0x8eb6, .data3 = 0x48f0, .data4 = .{ 0xab, 0xce, 0xc1, 0xb2, 0x11, 0xe6, 0x27, 0xc3 } };",
    ) != null);

    // IClosable.Close: void-returning, no trailing out param.
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "pub fn Close(self: *const IClosable) callconv(.winapi) HRESULT {",
    ) != null);

    // Many interfaces should have been emitted.
    var count: usize = 0;
    var search = out;
    while (std.mem.indexOf(u8, search, "pub const I")) |idx| {
        count += 1;
        search = search[idx + 1 ..];
    }
    try std.testing.expect(count > 5);
}

/// Emit opaque handle structs for every WinRT runtime class in
/// `namespace`. A runtime class is a `TypeDef` that:
///
///   * is not an interface (`tdInterface` clear),
///   * is not `System.ValueType` / `System.Enum` / `System.MulticastDelegate`
///     derived,
///   * extends `System.Object`.
///
/// This is what vtbls produced by `emitInterfaceVtbls` reference when
/// a method returns or consumes a runtime class (e.g.
/// `IUriRuntimeClassFactory.CreateUri` returns `**Uri`). Emitting
/// these as `extern struct { vtable: *const anyopaque }` gives the
/// generated code a valid, pointer-compatible destination for those
/// references; resolving the default interface to produce a typed
/// vtable pointer is a later slice.
pub fn emitRuntimeClasses(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    namespace: []const u8,
    cross: *CrossNsSet,
) !void {
    const VISIBILITY_MASK: u32 = 0x7;
    const VIS_NOT_PUBLIC: u32 = 0x0;
    const VIS_PUBLIC: u32 = 0x1;

    const rows = file.rowCount(.type_def);
    var row: u32 = 0;
    while (row < rows) : (row += 1) {
        if (!std.mem.eql(u8, file.str(.type_def, row, 2), namespace)) continue;

        const flags = file.cell(.type_def, row, 0);
        const vis = flags & VISIBILITY_MASK;
        if (vis != VIS_NOT_PUBLIC and vis != VIS_PUBLIC) continue;
        if ((flags & TYPE_ATTR_INTERFACE) != 0) continue;

        const extends_tok = file.cell(.type_def, row, 3);
        if (extends_tok == 0) continue;
        const base = winmd.resolveTypeDefOrRefName(file, extends_tok) catch continue;
        if (!std.mem.eql(u8, base.namespace, "System")) continue;
        if (!std.mem.eql(u8, base.name, "Object")) continue;

        const name = file.str(.type_def, row, 1);
        if (std.mem.indexOfScalar(u8, name, '`') != null) continue;

        // Resolve the default interface, if present. Every WinRT
        // runtime class has at most one InterfaceImpl row carrying a
        // `DefaultAttribute`; its `Interface` column (a TypeDefOrRef
        // coded index) is the default-interface type whose vtable
        // layout is what a `*<Class>` handle really points at.
        const default_name = defaultInterface(file, row);

        if (default_name) |tn| {
            // Emit a typed vtable pointer only when the default
            // interface lives in the same namespace — cross-namespace
            // imports land in a later slice. Generic default
            // interfaces (IVector`1 etc.) still fall back to opaque
            // because their `_Vtbl` symbol isn't emitted either.
            const same_ns = std.mem.eql(u8, tn.namespace, namespace);
            const is_generic = std.mem.indexOfScalar(u8, tn.name, '`') != null;
            if (same_ns and !is_generic) {
                try writer.print(
                    \\pub const {s} = extern struct {{
                    \\    vtable: *const {s}_Vtbl,
                    \\
                , .{ name, tn.name });
                try writeClassNames(writer, namespace, name);
                try writeActivateMethod(writer, arena, file, row, name, tn.name);
                try writeFactoryAlias(writer, arena, file, row, namespace, cross);
                try writeStaticsAliases(writer, arena, file, row, namespace, cross);
                try writer.writeAll("};\n");
                continue;
            }
        }

        try writer.print(
            \\pub const {s} = extern struct {{
            \\    vtable: *const anyopaque,
            \\
        , .{name});
        try writeClassNames(writer, namespace, name);
        try writeFactoryAlias(writer, arena, file, row, namespace, cross);
        try writeStaticsAliases(writer, arena, file, row, namespace, cross);
        try writer.writeAll("};\n");
    }
}

/// Emit a `pub fn activate() !*Self` convenience method inside a
/// runtime-class body when the class can be default-constructed via
/// the universal `IActivationFactory::ActivateInstance` path.
///
/// Gating: only emitted when `hasParameterlessActivation` is true for
/// `class_row`. Classes whose `[Activatable]` attributes all name a
/// typed factory (e.g. `Windows.Foundation.Uri`) construct through
/// that factory instead and never receive this method.
///
/// Signature convention: returns a raw pointer to the runtime-class
/// handle itself (`*Self`), not a `Com(...)` wrapper. The handle's
/// layout is `extern struct { vtable: *const <DefaultInterface>_Vtbl }`
/// — identical to the raw COM pointer `activateInstance` hands back,
/// so the trailing `@ptrCast` is pure type punning. The caller owns
/// one reference and must `Release` through the default-interface
/// vtable before dropping the pointer.
///
/// The `default_iface_name` is the bare type name of the default
/// interface (e.g. `"IJsonObject"`), used to name its `_Vtbl` symbol.
/// It must live in the same projectable namespace as the class — the
/// caller has already checked `same_ns and !is_generic` before invoking
/// this helper, so cross-namespace defaults are not handled here.
fn writeActivateMethod(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    class_row: u32,
    class_name: []const u8,
    default_iface_name: []const u8,
) !void {
    if (!hasParameterlessActivation(arena, file, class_row)) return;
    try writer.print(
        \\    pub fn activate() !*{s} {{
        \\        const raw = try win_core.activateInstance({s}_Vtbl, &NAME_W);
        \\        return @ptrCast(raw);
        \\    }}
        \\
    , .{ class_name, default_iface_name });
}

/// Emit the fully-qualified runtime class name as two compile-time
/// constants inside a class's `extern struct` body:
///   - `NAME`: UTF-8 `[]const u8`, handy for logs and diagnostics.
///   - `NAME_W`: UTF-16 LE array, directly consumable by
///     `win_core.activationFactory` (which takes `[]const u16`)
///     and other WinRT string APIs. Runtime class names are ASCII
///     by contract, so each byte widens 1:1 to a u16 code unit.
fn writeClassNames(
    writer: *std.Io.Writer,
    namespace: []const u8,
    name: []const u8,
) !void {
    try writer.print("    pub const NAME: []const u8 = \"{s}.{s}\";\n", .{ namespace, name });
    const total_len = namespace.len + 1 + name.len;
    try writer.print("    pub const NAME_W: [{d}]u16 = .{{", .{total_len});
    var first = true;
    for (namespace) |b| {
        if (!first) try writer.writeAll(",");
        try writer.print(" {d}", .{b});
        first = false;
    }
    try writer.print(", {d}", .{@as(u8, '.')});
    for (name) |b| {
        try writer.print(", {d}", .{b});
    }
    try writer.writeAll(" };\n");
}

/// Emit `pub const Factory = <FactoryInterface>;` inside a runtime
/// class body when the class carries an `ActivatableAttribute` whose
/// first positional argument is a `System.Type` naming the factory
/// interface (i.e. `[Activatable(typeof(IFooFactory), version)]`).
///
/// Classes with only the parameterless `[Activatable(version)]`
/// overload activate through the generic `IActivationFactory` and
/// need no class-specific alias — they are skipped.
///
/// When the factory lives in a different projectable namespace
/// (`Windows.*`) the alias is qualified through the namespace import
/// block: `pub const Factory = @"Windows.Foo".IFooFactory;`, and the
/// factory's namespace is recorded in `cross` so `emitNamespace`
/// threads the matching `@import` into the file header. Generic
/// factory interfaces and non-projectable namespaces are dropped
/// silently.
///
/// The emitted alias names the factory's *handle* type (not its
/// `_Vtbl`) so callers reach `.IID`, the IUnknown wrappers, and any
/// typed method wrappers the factory interface exposes. For an
/// activation call they then pass the vtbl type explicitly, e.g.
/// `win_core.activationFactory(IUriRuntimeClassFactory_Vtbl,
/// &Uri.Factory.IID, &Uri.NAME_W)`.
fn writeFactoryAlias(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    class_row: u32,
    namespace: []const u8,
    cross: *CrossNsSet,
) !void {
    const factory = activationFactoryName(arena, file, class_row) orelse return;
    if (std.mem.indexOfScalar(u8, factory.name, '`') != null) return;
    if (std.mem.eql(u8, factory.namespace, namespace)) {
        try writer.print("    pub const Factory = {s};\n", .{factory.name});
    } else if (isProjectableNs(factory.namespace)) {
        try cross.put(arena, factory.namespace, {});
        try writer.print("    pub const Factory = @\"{s}\".{s};\n", .{ factory.namespace, factory.name });
    }
}

/// Scan the custom attributes on runtime-class row `class_row` for
/// an `ActivatableAttribute` whose first positional argument is a
/// `System.Type` — i.e. the explicit-factory overload
/// `[Activatable(typeof(IFooFactory), version)]`. Returns the
/// resolved `TypeName` of that factory interface.
///
/// Classes can carry several `ActivatableAttribute` rows (one per
/// contract version plus zero or more static-factory siblings). The
/// first typed overload wins — in practice every class has at most
/// one activation factory, and the version/contract ordering is not
/// relevant for codegen.
///
/// Returns null when:
///   - the class has no `ActivatableAttribute`,
///   - every attribute uses the parameterless `[Activatable(version)]`
///     overload (generic `IActivationFactory` path), or
///   - the arg blob cannot be decoded (malformed metadata).
fn activationFactoryName(
    arena: std.mem.Allocator,
    file: *const winmd.File,
    class_row: u32,
) ?winmd.TypeName {
    const range = winmd.attributes(file, .type_def, class_row);
    var i = range.start;
    while (i < range.end) : (i += 1) {
        const tn = winmd.attributeName(file, i) orelse continue;
        if (!std.mem.eql(u8, tn.name, "ActivatableAttribute")) continue;

        const args = winmd.readAttributeArgs(arena, file, i) catch continue;
        if (args.len == 0) continue;
        switch (args[0].value) {
            .type_name => |factory| return factory,
            else => continue,
        }
    }
    return null;
}

/// Does this runtime class carry any parameterless `[Activatable]` attribute?
///
/// A WinRT class can be default-constructed when at least one of its
/// `ActivatableAttribute` rows uses the *un*-typed overload — i.e. the
/// first positional arg is a `uint` contract version rather than a
/// `System.Type` factory. That overload tells the runtime "use the
/// universal `IActivationFactory::ActivateInstance`"; it's the code
/// path behind `winrt::default_activation_factory` in C++/WinRT and
/// `IActivationFactory` in windows-rs.
///
/// A class can expose both overloads (a typed custom factory *and* a
/// parameterless one). We only care whether at least one parameterless
/// row exists — that's the signal to emit an `activate()` convenience.
fn hasParameterlessActivation(
    arena: std.mem.Allocator,
    file: *const winmd.File,
    class_row: u32,
) bool {
    const range = winmd.attributes(file, .type_def, class_row);
    var i = range.start;
    while (i < range.end) : (i += 1) {
        const tn = winmd.attributeName(file, i) orelse continue;
        if (!std.mem.eql(u8, tn.name, "ActivatableAttribute")) continue;

        const args = winmd.readAttributeArgs(arena, file, i) catch continue;
        if (args.len == 0) continue;
        switch (args[0].value) {
            // Typed factory overload; keep looking for a parameterless sibling.
            .type_name => continue,
            // Any non-type first arg (uint version in practice) means the
            // parameterless `IActivationFactory` path applies.
            else => return true,
        }
    }
    return false;
}

/// Emit zero or more `Statics` aliases on a runtime class's body —
/// one per `[Static(typeof(IFooStatics), version)]` custom attribute.
/// A class may advertise several statics interfaces across contract
/// versions (e.g. `IUriRuntimeClassStatics` plus
/// `IUriRuntimeClassStatics2`); the aliases are numbered in the
/// order metadata presents them:
///
///     pub const Statics  = IUriRuntimeClassStatics;
///     pub const Statics2 = IUriRuntimeClassStatics2;
///
/// Callers reach the IID via `Class.Statics.IID` and activate via
/// `win_core.activationFactory(IFooStatics_Vtbl, &Class.Statics.IID,
/// &Class.NAME_W)` — the same shape as `Factory`.
///
/// Cross-namespace statics interfaces (inside another `Windows.*`
/// namespace) are qualified via the namespace import block and
/// recorded in `cross`; generic and non-projectable interfaces are
/// skipped silently.
fn writeStaticsAliases(
    writer: *std.Io.Writer,
    arena: std.mem.Allocator,
    file: *const winmd.File,
    class_row: u32,
    namespace: []const u8,
    cross: *CrossNsSet,
) !void {
    const range = winmd.attributes(file, .type_def, class_row);
    var i = range.start;
    var index: u32 = 0;
    while (i < range.end) : (i += 1) {
        const tn = winmd.attributeName(file, i) orelse continue;
        if (!std.mem.eql(u8, tn.name, "StaticAttribute")) continue;

        const args = winmd.readAttributeArgs(arena, file, i) catch continue;
        if (args.len == 0) continue;
        const statics = switch (args[0].value) {
            .type_name => |t| t,
            else => continue,
        };
        if (std.mem.indexOfScalar(u8, statics.name, '`') != null) continue;

        const same_ns = std.mem.eql(u8, statics.namespace, namespace);
        if (!same_ns and !isProjectableNs(statics.namespace)) continue;

        index += 1;
        if (same_ns) {
            if (index == 1) {
                try writer.print("    pub const Statics = {s};\n", .{statics.name});
            } else {
                try writer.print("    pub const Statics{d} = {s};\n", .{ index, statics.name });
            }
        } else {
            try cross.put(arena, statics.namespace, {});
            if (index == 1) {
                try writer.print("    pub const Statics = @\"{s}\".{s};\n", .{ statics.namespace, statics.name });
            } else {
                try writer.print("    pub const Statics{d} = @\"{s}\".{s};\n", .{ index, statics.namespace, statics.name });
            }
        }
    }
}

/// Emit an opaque handle struct for every WinRT delegate in
/// `namespace`. Delegates (function-pointer contracts like
/// `AsyncActionCompletedHandler`) are TypeDefs whose base is
/// `System.MulticastDelegate`. Full call-syntax support is deferred —
/// for now we just make cross-references to the name resolve so vtbl
/// slots that pass a `*DelegateName` compile.
pub fn emitDelegates(
    writer: *std.Io.Writer,
    file: *const winmd.File,
    namespace: []const u8,
) !void {
    const rows = file.rowCount(.type_def);
    var row: u32 = 0;
    while (row < rows) : (row += 1) {
        if (!std.mem.eql(u8, file.str(.type_def, row, 2), namespace)) continue;

        const flags = file.cell(.type_def, row, 0);
        if ((flags & TYPE_ATTR_INTERFACE) != 0) continue;

        const extends_tok = file.cell(.type_def, row, 3);
        if (extends_tok == 0) continue;
        const base = winmd.resolveTypeDefOrRefName(file, extends_tok) catch continue;
        if (!std.mem.eql(u8, base.namespace, "System")) continue;
        if (!std.mem.eql(u8, base.name, "MulticastDelegate")) continue;

        const name = file.str(.type_def, row, 1);
        if (std.mem.indexOfScalar(u8, name, '`') != null) continue;

        try writer.print("pub const {s} = opaque {{}};\n", .{name});
    }
}

/// Return the default interface of the runtime-class TypeDef row, or
/// null if the class has no `DefaultAttribute`-tagged InterfaceImpl.
///
/// InterfaceImpl (§II.22.23) is sorted by Class, so we binary-search
/// for the rows belonging to `class_row` (values are stored 1-based)
/// and scan for the one with a `DefaultAttribute` custom attribute.
fn defaultInterface(file: *const winmd.File, class_row: u32) ?winmd.TypeName {
    const impls = file.equalRange(.interface_impl, 0, class_row + 1);
    var i = impls.start;
    while (i < impls.end) : (i += 1) {
        if (!winmd.hasAttribute(file, .interface_impl, i, "DefaultAttribute")) continue;
        const iface_tok = file.cell(.interface_impl, i, 1);
        return winmd.resolveTypeDefOrRefName(file, iface_tok) catch null;
    }
    return null;
}

test "emitRuntimeClasses writes Uri handle" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    var cross: CrossNsSet = .empty;

    try emitRuntimeClasses(&buf.writer, arena.allocator(), &file, "Windows.Foundation", &cross);
    const out = buf.written();

    // `Uri`'s default interface is `IUriRuntimeClass` — same namespace,
    // non-generic — so we expect a typed vtable pointer plus both the
    // UTF-8 `NAME` and UTF-16 `NAME_W` compile-time constants, plus a
    // `Factory` alias pointing at `IUriRuntimeClassFactory` (from
    // `[Activatable(typeof(IUriRuntimeClassFactory), ...)]`).
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Uri = extern struct {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "vtable: *const IUriRuntimeClass_Vtbl,") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const NAME: []const u8 = \"Windows.Foundation.Uri\";") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const NAME_W: [22]u16 = .{ 87, 105, 110, 100, 111, 119, 115, 46, 70, 111, 117, 110, 100, 97, 116, 105, 111, 110, 46, 85, 114, 105 };") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Factory = IUriRuntimeClassFactory;") != null);
    // `Uri` carries `[Static(typeof(IUriEscapeStatics), ...)]`, the
    // home of `UnescapeComponent` / `EscapeComponent`.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Statics = IUriEscapeStatics;") != null);
    // `GuidHelper` and `PropertyValue` are static-only runtime
    // classes in the same namespace — both should pick up the alias.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Statics = IGuidHelperStatics;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Statics = IPropertyValueStatics;") != null);

    // WwwFormUrlDecoder is another Windows.Foundation runtime class.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const WwwFormUrlDecoder = extern struct {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const NAME: []const u8 = \"Windows.Foundation.WwwFormUrlDecoder\";") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const NAME_W: [36]u16 = .{") != null);

    // `Uri` activates only through its typed factory
    // (`[Activatable(typeof(IUriRuntimeClassFactory), ...)]` — no
    // parameterless overload), so the `activate()` convenience must
    // NOT be emitted.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub fn activate") == null);

    // No interface names should appear here — those go through
    // `emitInterfaceHandles`.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const IStringable") == null);
}

test "emitRuntimeClasses emits activate() on parameterless WinRT classes" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    var cross: CrossNsSet = .empty;

    try emitRuntimeClasses(&buf.writer, arena.allocator(), &file, "Windows.Data.Json", &cross);
    const out = buf.written();

    // `JsonObject` and `JsonArray` both carry parameterless
    // `[Activatable(version)]` attributes — they should pick up the
    // default-construction convenience that delegates to
    // `win_core.activateInstance`.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const JsonObject = extern struct {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub fn activate() !*JsonObject {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "        const raw = try win_core.activateInstance(IJsonObject_Vtbl, &NAME_W);") != null);

    try std.testing.expect(std.mem.indexOf(u8, out, "pub const JsonArray = extern struct {") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub fn activate() !*JsonArray {") != null);

    // `JsonValue` has only `[Static(...)]` attributes — no activation
    // at all, not even typed — so no `activate()` should be emitted
    // on it.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const JsonValue = extern struct {") != null);
    // Scan the slice of `out` starting at `JsonValue` up to the next
    // top-level `pub const ` (i.e. the following class) for any
    // `pub fn activate`. This is a stronger check than a raw
    // `indexOf` on the whole buffer since JsonObject/JsonArray
    // legitimately carry the method.
    const jv_start = std.mem.indexOf(u8, out, "pub const JsonValue = extern struct {").?;
    const jv_end_rel = std.mem.indexOf(u8, out[jv_start..], "\n};\n").?;
    const jv_body = out[jv_start .. jv_start + jv_end_rel];
    try std.testing.expect(std.mem.indexOf(u8, jv_body, "pub fn activate") == null);
}

test "emitDelegates writes opaque handles for WinRT delegates" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    try emitDelegates(&buf.writer, &file, "Windows.Foundation");
    const out = buf.written();

    // AsyncActionCompletedHandler / DeferralCompletedHandler are
    // non-generic delegates in Windows.Foundation.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const AsyncActionCompletedHandler = opaque {};") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const DeferralCompletedHandler = opaque {};") != null);

    // Generic-arity delegates (AsyncOperationCompletedHandler`1 etc.)
    // are skipped — no backticks in the output.
    try std.testing.expect(std.mem.indexOfScalar(u8, out, '`') == null);

    // Interfaces and runtime classes must not leak into this emitter.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const IStringable") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const Uri ") == null);
}

test "emitNamespace composes all sub-emitters for Windows.Foundation" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    try emitNamespace(&buf.writer, arena.allocator(), &file, "Windows.Foundation");
    const out = buf.written();

    // Header establishes the win-core dependency and bridges the
    // primitives each sub-emitter references by bare name.
    try std.testing.expect(std.mem.indexOf(u8, out, "const win_core = @import(\"win-core\");") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "const HRESULT = win_core.HRESULT;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "const HSTRING = win_core.HSTRING;") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "const IInspectable_Vtbl = win_core.IInspectable_Vtbl;") != null);

    // One representative from each sub-emitter — ordering matters
    // because typed vtbls reference handles declared earlier.
    const iid = std.mem.indexOf(u8, out, "pub const IID_IStringable: GUID = .{").?;
    const enum_async = std.mem.indexOf(u8, out, "pub const AsyncStatus = enum(i32)").?;
    const point = std.mem.indexOf(u8, out, "pub const Point = extern struct {").?;
    const handle = std.mem.indexOf(u8, out, "pub const IStringable = extern struct {").?;
    const rt_class = std.mem.indexOf(u8, out, "pub const Uri = extern struct {").?;
    const vtbl = std.mem.indexOf(u8, out, "pub const IStringable_Vtbl = extern struct {").?;

    try std.testing.expect(iid < enum_async);
    try std.testing.expect(enum_async < point);
    try std.testing.expect(point < handle);
    try std.testing.expect(handle < rt_class);
    try std.testing.expect(rt_class < vtbl);
}

test "emitNamespace qualifies cross-namespace refs and emits import aliases" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    // Windows.Globalization pulls types from Windows.Foundation and
    // Windows.System (e.g. `User`, `DateTime`) — a known-busy namespace
    // for exercising the cross-ns emit path.
    try emitNamespace(&buf.writer, arena.allocator(), &file, "Windows.Globalization");
    const out = buf.written();

    // Each referenced namespace gets a `const @"<ns>" = @import("<ns>.zig");`
    // line emitted before the body.
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "const @\"Windows.Foundation\" = @import(\"Windows.Foundation.zig\");",
    ) != null);

    // Qualified references appear in vtbl method signatures. Pick
    // `DateTime` (a `Windows.Foundation` value type) since it shows up
    // as a `*@"Windows.Foundation".DateTime` out-param in Calendar's
    // IClosable-adjacent methods.
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "@\"Windows.Foundation\".DateTime",
    ) != null);

    // Same-namespace references (Calendar → Calendar) must stay
    // unqualified so we don't uselessly bloat every vtbl slot.
    try std.testing.expect(std.mem.indexOf(u8, out, "@\"Windows.Globalization\"") == null);

    // The import block must come before the first declaration.
    const import_idx = std.mem.indexOf(u8, out, "@import(\"Windows.Foundation.zig\")").?;
    if (std.mem.indexOf(u8, out, "pub const ")) |decl_idx| {
        try std.testing.expect(import_idx < decl_idx);
    }
}

test "emitNamespace skips generic-arity typedefs (no backticks in output)" {
    const bytes = @embedFile("Windows.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    // Windows.Foundation contains `IAsyncOperation\`1`, `IReference\`1`,
    // etc. Their names contain a backtick which is not a legal Zig
    // identifier character, and instantiating WinRT generics is
    // deferred to a later phase — so emitted output must contain no
    // literal backticks anywhere.
    try emitNamespace(&buf.writer, arena.allocator(), &file, "Windows.Foundation");
    const out = buf.written();

    try std.testing.expect(std.mem.indexOfScalar(u8, out, '`') == null);

    // Spot check: non-generic declarations are still there.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const IID_IStringable") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const AsyncStatus") != null);
}

test "emitFreeFunctions emits kernel32 exports for Windows.Win32.Foundation" {
    const bytes = @embedFile("Windows.Win32.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    var cross: CrossNsSet = .empty;
    try emitFreeFunctions(&buf.writer, arena.allocator(), &file, "Windows.Win32.Foundation", &cross);
    const out = buf.written();

    // CloseHandle(HANDLE) -> BOOL. HANDLE is a typedef over *mut c_void
    // in Win32 metadata, which the first-slice mapper renders as a
    // pointer; the exact spelling can shift as type support grows, so
    // anchor on the fixed framing instead.
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "pub extern \"KERNEL32\" fn CloseHandle(",
    ) != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "callconv(.winapi)") != null);

    // Every emitted line must use the extern / callconv framing —
    // there should never be a bare `fn ` outside `callconv(.winapi)`.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub extern ") != null);
}

test "emitFreeFunctions uses @extern for renamed P/Invoke (RtlGenRandom)" {
    const bytes = @embedFile("Windows.Win32.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    var cross: CrossNsSet = .empty;
    try emitFreeFunctions(&buf.writer, arena.allocator(), &file, "Windows.Win32.Security.Authentication.Identity", &cross);
    const out = buf.written();

    // RtlGenRandom is exported from ADVAPI32 under the real name
    // "SystemFunction036" — a textbook rename that requires
    // `@extern(.., .{ .name = ..., .library_name = ... })`.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const RtlGenRandom: *const fn ") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "= @extern(*const fn ") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".name = \"SystemFunction036\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, ".library_name = \"ADVAPI32\"") != null);
}

test "emitConstants emits primitive Win32 constants" {
    const bytes = @embedFile("Windows.Win32.winmd");
    var file = try winmd.parse(bytes);

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    // Windows.Win32.Storage.FileSystem is a dense source of
    // primitive integer constants (MAX_PATH, FILE_* flags, …).
    try emitConstants(&buf.writer, arena.allocator(), &file, "Windows.Win32.Storage.FileSystem");
    const out = buf.written();

    // At least one `pub const NAME: u32 = ...;` must appear — the
    // namespace has hundreds of u32 flag constants.
    try std.testing.expect(std.mem.indexOf(u8, out, ": u32 = ") != null);

    // Every emitted line must start with `pub const ` (no stray
    // output from unsupported field types).
    var it = std.mem.splitScalar(u8, out, '\n');
    while (it.next()) |line| {
        if (line.len == 0) continue;
        try std.testing.expect(std.mem.startsWith(u8, line, "pub const "));
    }
}

test "emitStructs suppresses HRESULT and BOOL in Windows.Win32.Foundation" {
    const bytes = @embedFile("Windows.Win32.winmd");
    var file = try winmd.parse(bytes);
    _ = &file;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var buf: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer buf.deinit();

    var cross: CrossNsSet = .empty;

    try emitStructs(&buf.writer, arena.allocator(), &file, "Windows.Win32.Foundation");
    _ = &cross;
    const out = buf.written();

    // Prelude aliases must NOT be re-emitted from metadata as
    // `pub const HRESULT = extern struct ...`; they resolve through
    // `win_core` via the prelude aliases written by emitNamespace.
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const HRESULT = extern struct") == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pub const BOOL = extern struct") == null);
}
