//! Comptime `project()` — materializes Win32 extern function
//! pointers from a filter of `(namespace, method_name)` pairs.
//!
//! Pipeline:
//!
//!   filter → index.<ns>.method_def_by_name.get(name) → MethodRecord
//!            ↓
//!         sig.decode(record.signature) → Sig
//!            ↓
//!         map each Ty to a Zig type (primitives inline,
//!         value_ref/class_ref through index.<ns>.resolveTypeRef
//!         + alias table)
//!            ↓
//!         @Type(.{ .@"fn" = ... }) → *const FnType
//!            ↓
//!         @extern(FnPtr, .{ .name, .library_name })
//!
//! The returned type is a `struct` with one function-pointer
//! *field* per requested method. Consumers call
//!
//!     const win = win_sys.project(.{
//!         .@"Windows.Win32.Foundation" = .{ "GetLastError" },
//!     });
//!     const e = win.GetLastError();
//!
//! Struct fields are used instead of decls because `@Type` cannot
//! synthesize `extern` declarations dynamically in Zig 0.16 — but
//! it can synthesize a struct whose fields are function-pointer
//! types, which we initialize via `@extern` in the `project()`
//! factory. Functionally equivalent to calling an extern fn;
//! the cost is an extra indirection.

const std = @import("std");
const sig_mod = @import("sig.zig");
const generated = @import("generated/mod.zig");

/// Generated per-namespace index modules. Exposed publicly so
/// samples and downstream code can reference primitive integer
/// constants emitted alongside the method table — e.g.
/// `win_sys.index.@"Windows.Win32.Storage.FileSystem".GENERIC_WRITE`.
///
/// Single source of truth is `generated/mod.zig`, regenerated by
/// `zig build bindings` (which invokes `winbindgen --emit-mod`).
pub const index = generated.index;

/// Consult the generator-emitted `aliases` block in the TypeRef's
/// own namespace index module. Returns the backing integer type
/// for `System.Enum`-extending TypeDefs (WIN32_ERROR, THREAD_ACCESS_RIGHTS,
/// …) or null if the namespace has no aliases block or the name
/// isn't declared there.
///
/// This retires the majority of `fnTypeForAlias` by moving the
/// source of truth into the `.winmd` — new enums show up without
/// a code edit. Shapes the generator can't derive yet (handles,
/// strings, opaque structs) stay in `fnTypeForAlias`.
fn winmdAlias(comptime ns: []const u8, comptime name: []const u8) ?type {
    if (!@hasDecl(index, ns)) return null;
    const ns_idx = @field(index, ns);
    if (!@hasDecl(ns_idx, "aliases")) return null;
    const aliases = ns_idx.aliases;
    if (!@hasDecl(aliases, name)) return null;
    return @field(aliases, name);
}

/// Consult the generator-emitted `<ns>.structs.zig` sidecar for a
/// concrete `extern struct`/`extern union` matching the TypeRef. This
/// retires the hand-listed layout-exposed struct aliases (FILETIME,
/// WIN32_FIND_DATAW, SYSTEM_INFO, …) by pulling directly from the
/// namespace the TypeRef points at — no central map required.
///
/// Returns null if the namespace has no generated structs sidecar, or
/// if the sidecar doesn't declare a type of that name (e.g. opaque
/// aliases that stay in `fnTypeForAlias`).
fn structAlias(comptime ns: []const u8, comptime name: []const u8) ?type {
    if (!@hasDecl(generated_structs, ns)) return null;
    const ns_structs = @field(generated_structs, ns);
    if (!@hasDecl(ns_structs, name)) return null;
    return @field(ns_structs, name);
}

/// Hand-listed `Windows.Win32.Foundation`-area TypeRefs that neither
/// `winmdAlias` (no matching entry in the generated `aliases` block)
/// nor `structAlias` (no matching decl in any `<ns>.structs.zig`
/// sidecar) can resolve. Currently this reduces to a single entry:
/// FARPROC, which is a raw function-pointer alias GetProcAddress
/// returns — callers `@ptrCast` it to the concrete signature they
/// need so the sys layer surfaces it as `?*const anyopaque`.
fn fnTypeForAlias(comptime name: []const u8) ?type {
    if (std.mem.eql(u8, name, "FARPROC")) return ?*const anyopaque;

    return null;
}

/// Generated struct sidecars. Each `<ns>.structs.zig` is
/// produced by `winbindgen --structs <ns>` and contains every
/// `extern struct`/`extern union` in that namespace that the
/// generator can fully represent (no generics, no SZARRAY, no
/// unresolved nested types).
///
/// Single source of truth is `generated/mod.zig`, regenerated by
/// `zig build bindings` (which invokes `winbindgen --emit-mod`).
const generated_structs = generated.structs;

/// Concrete struct projections. Public so callers can name the
/// types in their own declarations (e.g. `var fd: win_sys.structs
/// .WIN32_FIND_DATAW = undefined;`). Field names mirror the Win32
/// headers verbatim for grep-ability.
///
/// Types migrated onto `generated_structs` are re-exported here
/// so downstream callers keep working against `win_sys.structs.X`
/// while the source of truth moves into winbindgen output.
pub const structs = struct {
    /// §winbase.h. Projected from `Windows.Win32.Foundation.structs.zig`.
    pub const FILETIME = generated_structs.@"Windows.Win32.Foundation".FILETIME;

    /// §minwinbase.h. Projected from
    /// `Windows.Win32.Storage.FileSystem.structs.zig`. Out-param
    /// of FindFirstFileW / FindNextFileW. cFileName has room for
    /// MAX_PATH (260) wide chars including NUL; cAlternateFileName
    /// is the 8.3 short name (14 wide chars). Struct is 592 bytes.
    pub const WIN32_FIND_DATAW =
        generated_structs.@"Windows.Win32.Storage.FileSystem".WIN32_FIND_DATAW;

    /// §sysinfoapi.h. Projected from
    /// `Windows.Win32.System.SystemInformation.structs.zig`. Out-param
    /// of GetSystemInfo / GetNativeSystemInfo. Nested anonymous
    /// union/struct (`SYSTEM_INFO_0`, `SYSTEM_INFO_0_0`) are emitted
    /// as struct-scoped `pub const` decls inside the sidecar and
    /// resolved via Zig's struct-scope lookup; they are not part of
    /// this `structs` namespace. Size 48 on x86 / 56 on x64.
    pub const SYSTEM_INFO =
        generated_structs.@"Windows.Win32.System.SystemInformation".SYSTEM_INFO;

    /// Anonymous union inside SYSTEM_INFO. Re-exported from the
    /// sidecar's struct-scoped decl so existing callers that name it
    /// directly (e.g. layout asserts) keep working.
    pub const SYSTEM_INFO_0 = SYSTEM_INFO.SYSTEM_INFO_0;

    /// Anonymous struct inside SYSTEM_INFO_0. Re-exported for the
    /// same reason as `SYSTEM_INFO_0`.
    pub const SYSTEM_INFO_0_0 = SYSTEM_INFO_0.SYSTEM_INFO_0_0;

    /// §threadpoolapiset.h. Callback environment used to associate
    /// submissions with a private pool / cleanup group.
    pub const TP_CALLBACK_ENVIRON_V3 =
        generated_structs.@"Windows.Win32.System.Threading".TP_CALLBACK_ENVIRON_V3;

    /// §winuser.h. Projected from
    /// `Windows.Win32.UI.WindowsAndMessaging.structs.zig`. Passed by
    /// pointer to `RegisterClassA`. `lpfnWndProc` is a delegate-typed
    /// field surfaced as `?*const anyopaque`; assign with
    /// `@ptrCast(&wndproc)` where `wndproc` is an `extern "system" fn`.
    pub const WNDCLASSA =
        generated_structs.@"Windows.Win32.UI.WindowsAndMessaging".WNDCLASSA;

    /// §windef.h. Common rectangle used by USER32/GDI paint and layout APIs.
    pub const RECT =
        generated_structs.@"Windows.Win32.Foundation".RECT;

    /// §winuser.h. Out-param of `GetMessageA` / `PeekMessageA`. Fed
    /// (by value) to `TranslateMessage` and `DispatchMessageA`.
    pub const MSG =
        generated_structs.@"Windows.Win32.UI.WindowsAndMessaging".MSG;
};

/// Map a decoded `Ty` to a Zig type. `NamespaceIndex` must expose
/// a `resolveTypeRef(u32) ?TypeRefEntry` function (all generated
/// index files do).
fn tyToZigType(
    comptime NamespaceIndex: type,
    comptime method_name: []const u8,
    comptime t: sig_mod.Ty,
) type {
    const base: type = switch (t.kind) {
        .void => void,
        .bool => bool,
        .i8 => i8,
        .u8 => u8,
        .i16 => i16,
        .u16 => u16,
        .i32 => i32,
        .u32 => u32,
        .i64 => i64,
        .u64 => u64,
        .f32 => f32,
        .f64 => f64,
        .isize => isize,
        .usize => usize,
        .char => u16, // §II.23.1.16 CHAR is a 16-bit UTF-16 code unit.
        .value_ref, .class_ref => blk: {
            const resolved = NamespaceIndex.resolveTypeRef(t.coded_index) orelse
                @compileError("project: unresolved TypeRef in " ++ method_name ++
                    " (coded index missing from resolveTypeRef table)");
            // Three-tier lookup:
            //  1. The TypeRef's own namespace index may expose an
            //     `aliases` block — emitted by `winbindgen --index`
            //     for every `System.Enum`-extending TypeDef and every
            //     single-field typedef wrapper (BOOL/HRESULT/PWSTR/H*…).
            //     Covers all flag/status enums and NativeTypedef
            //     handles mechanically — no hand-list needed.
            //  2. The TypeRef's own namespace `structs` sidecar may
            //     declare a concrete `extern struct`/`extern union`
            //     with the same name. Retires the hand-listed layout-
            //     exposed aliases (FILETIME, WIN32_FIND_DATAW,
            //     SYSTEM_INFO) by pulling directly from the namespace.
            //  3. Hand-list in `fnTypeForAlias` for shapes the
            //     generator can't derive: PSID (no Value field,
            //     no NativeTypedefAttribute), FARPROC (function
            //     pointer), and opaque aliases like SECURITY_ATTRIBUTES
            //     and OVERLAPPED that are passed as null pointers.
            //  4. @compileError so missing TypeRefs surface at the
            //     call site rather than silently projecting as void.
            if (winmdAlias(resolved.namespace, resolved.name)) |a| break :blk a;
            if (structAlias(resolved.namespace, resolved.name)) |a| break :blk a;
            const aliased = fnTypeForAlias(resolved.name) orelse
                @compileError("project: no alias for TypeRef " ++
                    resolved.namespace ++ "." ++ resolved.name ++
                    " (referenced by " ++ method_name ++ ")");
            break :blk aliased;
        },
        .unsupported => @compileError("project: unsupported signature element in " ++ method_name),
    };

    var ty: type = base;
    var depth: u8 = 0;
    while (depth < t.ptrs) : (depth += 1) {
        // Win32 pointers in method signatures are C-style: may be
        // null, addressable element count unknown → `?*` (or
        // `?[*]` for explicitly array-shaped uses, but we can't
        // distinguish at this level). `?*T` round-trips through
        // the C ABI as a plain pointer.
        //
        // Special case: `Ptr<void>` (LPVOID) is the C idiom for an
        // opaque pointer. Zig's `?*void` is a zero-sized-pointer
        // oddity that refuses integer casts; `?*anyopaque` is the
        // idiomatic replacement and lets callers `@ptrCast`
        // arbitrary buffers through.
        if (depth == 0 and ty == void) {
            ty = anyopaque;
        }
        ty = ?*ty;
    }
    return ty;
}

fn fnTypeFor(
    comptime NamespaceIndex: type,
    comptime method_name: []const u8,
    comptime s: sig_mod.Sig,
) type {
    // ECMA-335 §II.23.2.1 HASTHIS on a P/Invoke method is
    // nonsensical — Win32 DLL exports are free functions. Error
    // rather than silently dropping the `this` slot.
    if (s.has_this) @compileError("project: HASTHIS unexpected on Win32 free function " ++ method_name);

    comptime var param_types: [sig_mod.MAX_PARAMS]type = undefined;
    comptime var param_attrs: [sig_mod.MAX_PARAMS]std.builtin.Type.Fn.Param.Attributes = undefined;
    comptime var i: usize = 0;
    inline while (i < s.param_count) : (i += 1) {
        param_types[i] = tyToZigType(NamespaceIndex, method_name, s.params_buf[i]);
        param_attrs[i] = .{};
    }

    const RetT = tyToZigType(NamespaceIndex, method_name, s.return_type);

    return @Fn(
        param_types[0..s.param_count],
        param_attrs[0..s.param_count],
        RetT,
        .{ .@"callconv" = .winapi },
    );
}

fn namespaceIndex(comptime ns: []const u8) type {
    return @field(index, ns);
}

/// Upper bound on methods per `project()` call. Picked generously so
/// real applications almost never hit it; exceeding it surfaces a
/// `@compileError` with guidance to split the filter across two
/// `project()` calls. Current comptime cost is roughly linear in the
/// filter size (see `benches/project_bench/main.zig`).
const MAX_PROJECT_METHODS: usize = 256;

/// Build the container struct type from the filter. One field per
/// requested method, typed `*const FnType` where FnType is
/// reconstructed from the method's signature blob.
fn ProjectType(comptime filter: anytype) type {
    // StaticStringMap.get() on the big namespace indexes
    // (Storage.FileSystem has 400+ entries, UI.WindowsAndMessaging
    // similar) blows the default 1000-branch quota after just a
    // handful of lookups. Bump generously -- comptime eval is still
    // one-shot per project() call.
    @setEvalBranchQuota(1_000_000);
    const Filter = @TypeOf(filter);
    comptime var total: usize = 0;
    inline for (@typeInfo(Filter).@"struct".fields) |nsf| {
        const names = @field(filter, nsf.name);
        inline for (@typeInfo(@TypeOf(names)).@"struct".fields) |_| total += 1;
    }

    comptime var names_buf: [MAX_PROJECT_METHODS][:0]const u8 = undefined;
    comptime var types_buf: [MAX_PROJECT_METHODS]type = undefined;
    comptime var attrs_buf: [MAX_PROJECT_METHODS]std.builtin.Type.StructField.Attributes = undefined;
    if (total > MAX_PROJECT_METHODS)
        @compileError(std.fmt.comptimePrint(
            "project: filter has {d} methods, cap is {d}. Split the filter across two project() calls.",
            .{ total, MAX_PROJECT_METHODS },
        ));

    comptime var idx: usize = 0;
    inline for (@typeInfo(Filter).@"struct".fields) |nsf| {
        const NsIdx = namespaceIndex(nsf.name);
        const names = @field(filter, nsf.name);
        inline for (@typeInfo(@TypeOf(names)).@"struct".fields) |namef| {
            const name: []const u8 = @field(names, namef.name);
            const rec = NsIdx.method_def_by_name.get(name) orelse
                @compileError("project: method not found in " ++ nsf.name ++ ": " ++ name);
            const s = sig_mod.decode(rec.signature) catch
                @compileError("project: signature decode failed for " ++ name);
            const FnT = fnTypeFor(NsIdx, name, s);
            const FnPtr = *const FnT;
            names_buf[idx] = name ++ "";
            types_buf[idx] = FnPtr;
            attrs_buf[idx] = .{};
            idx += 1;
        }
    }

    return @Struct(
        .auto,
        null,
        names_buf[0..total],
        types_buf[0..total],
        attrs_buf[0..total],
    );
}

/// Factory — pass a struct filter mapping namespace to a tuple of
/// method names. Returns a populated struct value whose fields
/// are the projected extern function pointers.
pub fn project(comptime filter: anytype) ProjectType(filter) {
    @setEvalBranchQuota(1_000_000);
    const T = ProjectType(filter);
    var out: T = undefined;
    inline for (@typeInfo(@TypeOf(filter)).@"struct".fields) |nsf| {
        const NsIdx = namespaceIndex(nsf.name);
        const names = @field(filter, nsf.name);
        inline for (@typeInfo(@TypeOf(names)).@"struct".fields) |namef| {
            const name: []const u8 = @field(names, namef.name);
            const rec = comptime NsIdx.method_def_by_name.get(name).?;
            const FnPtr = @FieldType(T, name);
            @field(out, name) = @extern(FnPtr, .{
                .name = rec.import,
                .library_name = rec.library,
            });
        }
    }
    return out;
}

// ---- Tests --------------------------------------------------------------

test "project: Foundation { GetLastError, SetLastError } type-checks" {
    const win = project(.{
        .@"Windows.Win32.Foundation" = .{ "GetLastError", "SetLastError" },
    });

    // Field types must match the decoded signatures. GetLastError
    // takes no params and returns WIN32_ERROR (u32 via alias).
    const GetLastErrorT = @TypeOf(win.GetLastError);
    try std.testing.expectEqual(@as(type, *const fn () callconv(.winapi) u32), GetLastErrorT);

    // SetLastError takes a WIN32_ERROR and returns void.
    const SetLastErrorT = @TypeOf(win.SetLastError);
    try std.testing.expectEqual(@as(type, *const fn (u32) callconv(.winapi) void), SetLastErrorT);
}

test "project: Foundation { SysAllocString } returns BSTR" {
    const win = project(.{
        .@"Windows.Win32.Foundation" = .{"SysAllocString"},
    });

    // SysAllocString(PCWSTR) -> BSTR. PCWSTR is itself a VALUETYPE
    // in Foundation, mapping to ?[*:0]u16 via the alias table.
    // BSTR also maps to ?[*:0]u16.
    const T = @TypeOf(win.SysAllocString);
    const info = @typeInfo(T).pointer.child;
    const fn_info = @typeInfo(info).@"fn";
    try std.testing.expectEqual(@as(u32, 1), fn_info.params.len);
    try std.testing.expectEqual(@as(?type, ?[*:0]u16), fn_info.return_type);
}

test "project: LibraryLoader { GetModuleHandleW, GetProcAddress, LoadLibraryW } type-checks" {
    // Cross-namespace projection: all three functions live in
    // System.LibraryLoader but take Foundation handles (HMODULE,
    // PWSTR, PSTR, BOOL) — resolved through LibraryLoader's own
    // resolveTypeRef table + the shared alias table.
    const win = project(.{
        .@"Windows.Win32.System.LibraryLoader" = .{
            "GetModuleHandleW",
            "GetProcAddress",
            "LoadLibraryW",
        },
    });

    // GetModuleHandleW(PCWSTR) -> HMODULE
    const GetModuleHandleWT = @TypeOf(win.GetModuleHandleW);
    try std.testing.expectEqual(
        @as(type, *const fn (?[*:0]u16) callconv(.winapi) ?*anyopaque),
        GetModuleHandleWT,
    );

    // GetProcAddress(HMODULE, PCSTR) -> FARPROC (opaque fn ptr)
    const GetProcAddressT = @TypeOf(win.GetProcAddress);
    try std.testing.expectEqual(
        @as(type, *const fn (?*anyopaque, ?[*:0]u8) callconv(.winapi) ?*const anyopaque),
        GetProcAddressT,
    );

    // LoadLibraryW(PCWSTR) -> HMODULE
    const LoadLibraryWT = @TypeOf(win.LoadLibraryW);
    try std.testing.expectEqual(
        @as(type, *const fn (?[*:0]u16) callconv(.winapi) ?*anyopaque),
        LoadLibraryWT,
    );
}

test "project: Threading { GetCurrentThreadId, Sleep } type-checks" {
    // Windows.Win32.System.Threading is the third namespace wired
    // through the comptime projection pipeline. These two APIs
    // exercise the simplest signature shapes:
    //   - GetCurrentThreadId(): u32            → 0 params, primitive return
    //   - Sleep(u32): void                     → 1 u32 param, void return
    // No TypeRefs involved, so this validates the primitive path
    // for a fresh namespace without depending on the alias table.
    const win = project(.{
        .@"Windows.Win32.System.Threading" = .{ "GetCurrentThreadId", "Sleep" },
    });

    try std.testing.expectEqual(
        @as(type, *const fn () callconv(.winapi) u32),
        @TypeOf(win.GetCurrentThreadId),
    );
    try std.testing.expectEqual(
        @as(type, *const fn (u32) callconv(.winapi) void),
        @TypeOf(win.Sleep),
    );
}

test "project: Console { GetStdHandle, GetConsoleCP } type-checks" {
    // Fourth namespace wired. Exercises two new VALUETYPE → u32
    // flag enum aliases added to the alias table:
    //   - STD_HANDLE    (param of GetStdHandle)
    //   - CONSOLE_MODE  (unused here but registered alongside)
    // Plus a no-alias primitive-only API (GetConsoleCP) as a
    // sanity check that the Console namespace resolves at all.
    const win = project(.{
        .@"Windows.Win32.System.Console" = .{ "GetStdHandle", "GetConsoleCP" },
    });

    // GetStdHandle(STD_HANDLE) -> HANDLE
    try std.testing.expectEqual(
        @as(type, *const fn (u32) callconv(.winapi) ?*anyopaque),
        @TypeOf(win.GetStdHandle),
    );

    // GetConsoleCP() -> u32
    try std.testing.expectEqual(
        @as(type, *const fn () callconv(.winapi) u32),
        @TypeOf(win.GetConsoleCP),
    );
}

test "project: WindowsAndMessaging { GetDesktopWindow, IsWindow } type-checks" {
    // Fifth namespace wired. Exercises the new HWND -> isize alias.
    // GetDesktopWindow() -> HWND is the minimal HWND-returning call;
    // IsWindow(HWND) -> BOOL exercises HWND as a parameter + BOOL return.
    const win = project(.{
        .@"Windows.Win32.UI.WindowsAndMessaging" = .{ "GetDesktopWindow", "IsWindow" },
    });

    try std.testing.expectEqual(
        @as(type, *const fn () callconv(.winapi) ?*anyopaque),
        @TypeOf(win.GetDesktopWindow),
    );
    try std.testing.expectEqual(
        @as(type, *const fn (?*anyopaque) callconv(.winapi) i32),
        @TypeOf(win.IsWindow),
    );
}

test "project: WindowsAndMessaging { MessageBoxW } type-checks" {
    // MessageBoxW(hwnd: HWND, text: PWSTR, caption: PWSTR, style: MESSAGEBOX_STYLE)
    //   -> MESSAGEBOX_RESULT.
    // The generator encodes both strings as PWSTR in the signature blob
    // (winmd collapses PCWSTR/PWSTR through the TypeRef tag); MESSAGEBOX_STYLE
    // maps to u32 (flag enum) and MESSAGEBOX_RESULT maps to i32 (signed
    // IDOK/IDCANCEL/... values, matching the windows-rs projection).
    const win = project(.{
        .@"Windows.Win32.UI.WindowsAndMessaging" = .{"MessageBoxW"},
    });

    try std.testing.expectEqual(
        @as(
            type,
            *const fn (?*anyopaque, ?[*:0]u16, ?[*:0]u16, u32) callconv(.winapi) i32,
        ),
        @TypeOf(win.MessageBoxW),
    );
}

test "project: Storage.FileSystem { CreateFileW, WriteFile, DeleteFileW } type-checks" {
    // CreateFileW signature:
    //   HANDLE CreateFileW(
    //       PCWSTR                    lpFileName,        -- PWSTR in winmd
    //       u32                       dwDesiredAccess,   -- bare u32 (no enum wrapper)
    //       FILE_SHARE_MODE           dwShareMode,       -- u32 alias
    //       SECURITY_ATTRIBUTES*      lpSecurityAttrs,   -- concrete struct via structAlias
    //       FILE_CREATION_DISPOSITION dwCreationDisposition, -- u32 alias
    //       FILE_FLAGS_AND_ATTRIBUTES dwFlagsAndAttributes,  -- u32 alias
    //       HANDLE                    hTemplateFile,
    //   );
    //
    // WriteFile(HANDLE, *const u8, u32, *u32, OVERLAPPED*) -> BOOL.
    //   OVERLAPPED resolves via structAlias to the concrete sidecar
    //   struct in `Windows.Win32.System.IO.structs`.
    //
    // DeleteFileW(PCWSTR) -> BOOL. Exercises a single-PWSTR API and
    // keeps the sample able to clean up its temp file without leaking.
    const win = project(.{
        .@"Windows.Win32.Storage.FileSystem" = .{ "CreateFileW", "WriteFile", "DeleteFileW" },
    });

    const SEC_ATTR = generated_structs.@"Windows.Win32.Security".SECURITY_ATTRIBUTES;
    const OVERLAPPED = generated_structs.@"Windows.Win32.System.IO".OVERLAPPED;

    try std.testing.expectEqual(
        @as(
            type,
            *const fn (?[*:0]u16, u32, u32, ?*SEC_ATTR, u32, u32, ?*anyopaque) callconv(.winapi) ?*anyopaque,
        ),
        @TypeOf(win.CreateFileW),
    );
    try std.testing.expectEqual(
        @as(
            type,
            *const fn (?*anyopaque, ?*u8, u32, ?*u32, ?*OVERLAPPED) callconv(.winapi) i32,
        ),
        @TypeOf(win.WriteFile),
    );
    try std.testing.expectEqual(
        @as(type, *const fn (?[*:0]u16) callconv(.winapi) i32),
        @TypeOf(win.DeleteFileW),
    );
}
